// Code generated by go-swagger; DO NOT EDIT.

package insights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetInsightsByAccountIDParams creates a new GetInsightsByAccountIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInsightsByAccountIDParams() *GetInsightsByAccountIDParams {
	return &GetInsightsByAccountIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInsightsByAccountIDParamsWithTimeout creates a new GetInsightsByAccountIDParams object
// with the ability to set a timeout on a request.
func NewGetInsightsByAccountIDParamsWithTimeout(timeout time.Duration) *GetInsightsByAccountIDParams {
	return &GetInsightsByAccountIDParams{
		timeout: timeout,
	}
}

// NewGetInsightsByAccountIDParamsWithContext creates a new GetInsightsByAccountIDParams object
// with the ability to set a context for a request.
func NewGetInsightsByAccountIDParamsWithContext(ctx context.Context) *GetInsightsByAccountIDParams {
	return &GetInsightsByAccountIDParams{
		Context: ctx,
	}
}

// NewGetInsightsByAccountIDParamsWithHTTPClient creates a new GetInsightsByAccountIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInsightsByAccountIDParamsWithHTTPClient(client *http.Client) *GetInsightsByAccountIDParams {
	return &GetInsightsByAccountIDParams{
		HTTPClient: client,
	}
}

/*
GetInsightsByAccountIDParams contains all the parameters to send to the API endpoint

	for the get insights by account ID operation.

	Typically these are written to a http.Request.
*/
type GetInsightsByAccountIDParams struct {

	/* XRequestID.

	   An unique ID for the request
	*/
	XRequestID *string

	/* Breakdown.

	     Designates how to break down result set into subsets. Values can be:
	- contact_button_type (divides results by profile component: BOOK_NOW, CALL, DIRECTION, EMAIL, INSTANT_EXPERIENCE, TEXT, UNDEFINED)
	- follow_type (breaks down by followers or non-followers: FOLLOWER, NON_FOLLOWER, UNKNOWN)
	- media_product_type (breaks down by surface: AD, FEED, REELS, STORY)
	- age (for demographic metrics)
	- city (for demographic metrics)
	- country (for demographic metrics)
	- gender (for demographic metrics)

	Only compatible with metric_type=total_value. See metric descriptions for compatible breakdowns.

	*/
	Breakdown *string

	/* InstagramAccountID.

	   Instagram Account ID (your app user's Instagram professional account ID)
	*/
	InstagramAccountID string

	/* Metric.

	     Required. Comma-separated list of metrics you want returned. Available metrics include:

	Interaction Metrics:
	- accounts_engaged (day period, total_value metric type)
	- comments (day period, total_value metric type, media_product_type breakdown)
	- engaged_audience_demographics (lifetime period, total_value metric type, age/city/country/gender breakdowns)
	- follows_and_unfollows (day period, total_value metric type, follow_type breakdown)
	- follower_demographics (lifetime period, total_value metric type, age/city/country/gender breakdowns)
	- impressions (day period, total_value/time_series metric type) - DEPRECATED for v22.0+
	- likes (day period, total_value metric type, media_product_type breakdown)
	- profile_links_taps (day period, total_value metric type, contact_button_type breakdown)
	- reach (day period, total_value/time_series metric type, media_product_type/follow_type breakdowns)
	- replies (day period, total_value metric type)
	- saved (day period, total_value metric type, media_product_type breakdown)
	- shares (day period, total_value metric type, media_product_type breakdown)
	- total_interactions (day period, total_value metric type, media_product_type breakdown)
	- views (day period, total_value metric type, follower_type/media_product_type breakdowns)

	*/
	Metric string

	/* MetricType.

	     Designates if you want the responses aggregated by time period or as a simple total. Values can be:
	- time_series (aggregate results by time period)
	- total_value (return results as a simple total, with breakdowns if requested)

	*/
	MetricType *string

	/* Period.

	     Required. Period aggregation. Values can be:
	- day (for interaction metrics)
	- lifetime (for demographic metrics)

	*/
	Period string

	/* Since.

	   Unix timestamp indicating start of range. The API will only include data created within this range (inclusive). If not included, API looks back 24 hours.

	   Format: int64
	*/
	Since *int64

	/* Timeframe.

	     Required for demographics-related metrics. Designates how far to look back for data. Values can be:
	- last_14_days (deprecated beginning with v20.0)
	- last_30_days (deprecated beginning with v20.0)
	- last_90_days (deprecated beginning with v20.0)
	- prev_month (deprecated beginning with v20.0)
	- this_month (returns data in the last 30 days)
	- this_week (returns data in the last 7 days)

	This parameter overrides since and until parameters.

	*/
	Timeframe *string

	/* Until.

	   Unix timestamp indicating end of range. The API will only include data created within this range (inclusive). If not included, API looks back 24 hours.

	   Format: int64
	*/
	Until *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get insights by account ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInsightsByAccountIDParams) WithDefaults() *GetInsightsByAccountIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get insights by account ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInsightsByAccountIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) WithTimeout(timeout time.Duration) *GetInsightsByAccountIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) WithContext(ctx context.Context) *GetInsightsByAccountIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) WithHTTPClient(client *http.Client) *GetInsightsByAccountIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) WithXRequestID(xRequestID *string) *GetInsightsByAccountIDParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithBreakdown adds the breakdown to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) WithBreakdown(breakdown *string) *GetInsightsByAccountIDParams {
	o.SetBreakdown(breakdown)
	return o
}

// SetBreakdown adds the breakdown to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) SetBreakdown(breakdown *string) {
	o.Breakdown = breakdown
}

// WithInstagramAccountID adds the instagramAccountID to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) WithInstagramAccountID(instagramAccountID string) *GetInsightsByAccountIDParams {
	o.SetInstagramAccountID(instagramAccountID)
	return o
}

// SetInstagramAccountID adds the instagramAccountId to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) SetInstagramAccountID(instagramAccountID string) {
	o.InstagramAccountID = instagramAccountID
}

// WithMetric adds the metric to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) WithMetric(metric string) *GetInsightsByAccountIDParams {
	o.SetMetric(metric)
	return o
}

// SetMetric adds the metric to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) SetMetric(metric string) {
	o.Metric = metric
}

// WithMetricType adds the metricType to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) WithMetricType(metricType *string) *GetInsightsByAccountIDParams {
	o.SetMetricType(metricType)
	return o
}

// SetMetricType adds the metricType to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) SetMetricType(metricType *string) {
	o.MetricType = metricType
}

// WithPeriod adds the period to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) WithPeriod(period string) *GetInsightsByAccountIDParams {
	o.SetPeriod(period)
	return o
}

// SetPeriod adds the period to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) SetPeriod(period string) {
	o.Period = period
}

// WithSince adds the since to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) WithSince(since *int64) *GetInsightsByAccountIDParams {
	o.SetSince(since)
	return o
}

// SetSince adds the since to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) SetSince(since *int64) {
	o.Since = since
}

// WithTimeframe adds the timeframe to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) WithTimeframe(timeframe *string) *GetInsightsByAccountIDParams {
	o.SetTimeframe(timeframe)
	return o
}

// SetTimeframe adds the timeframe to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) SetTimeframe(timeframe *string) {
	o.Timeframe = timeframe
}

// WithUntil adds the until to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) WithUntil(until *int64) *GetInsightsByAccountIDParams {
	o.SetUntil(until)
	return o
}

// SetUntil adds the until to the get insights by account ID params
func (o *GetInsightsByAccountIDParams) SetUntil(until *int64) {
	o.Until = until
}

// WriteToRequest writes these params to a swagger request
func (o *GetInsightsByAccountIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	if o.Breakdown != nil {

		// query param breakdown
		var qrBreakdown string

		if o.Breakdown != nil {
			qrBreakdown = *o.Breakdown
		}
		qBreakdown := qrBreakdown
		if qBreakdown != "" {

			if err := r.SetQueryParam("breakdown", qBreakdown); err != nil {
				return err
			}
		}
	}

	// path param instagram_account_id
	if err := r.SetPathParam("instagram_account_id", o.InstagramAccountID); err != nil {
		return err
	}

	// query param metric
	qrMetric := o.Metric
	qMetric := qrMetric
	if qMetric != "" {

		if err := r.SetQueryParam("metric", qMetric); err != nil {
			return err
		}
	}

	if o.MetricType != nil {

		// query param metric_type
		var qrMetricType string

		if o.MetricType != nil {
			qrMetricType = *o.MetricType
		}
		qMetricType := qrMetricType
		if qMetricType != "" {

			if err := r.SetQueryParam("metric_type", qMetricType); err != nil {
				return err
			}
		}
	}

	// query param period
	qrPeriod := o.Period
	qPeriod := qrPeriod
	if qPeriod != "" {

		if err := r.SetQueryParam("period", qPeriod); err != nil {
			return err
		}
	}

	if o.Since != nil {

		// query param since
		var qrSince int64

		if o.Since != nil {
			qrSince = *o.Since
		}
		qSince := swag.FormatInt64(qrSince)
		if qSince != "" {

			if err := r.SetQueryParam("since", qSince); err != nil {
				return err
			}
		}
	}

	if o.Timeframe != nil {

		// query param timeframe
		var qrTimeframe string

		if o.Timeframe != nil {
			qrTimeframe = *o.Timeframe
		}
		qTimeframe := qrTimeframe
		if qTimeframe != "" {

			if err := r.SetQueryParam("timeframe", qTimeframe); err != nil {
				return err
			}
		}
	}

	if o.Until != nil {

		// query param until
		var qrUntil int64

		if o.Until != nil {
			qrUntil = *o.Until
		}
		qUntil := swag.FormatInt64(qrUntil)
		if qUntil != "" {

			if err := r.SetQueryParam("until", qUntil); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
