// Code generated by go-swagger; DO NOT EDIT.

package insights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qcserestipy/instagram-media-insights-go-client/pkg/sdk-account/v24.0/models"
)

// GetInsightsByAccountIDReader is a Reader for the GetInsightsByAccountID structure.
type GetInsightsByAccountIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInsightsByAccountIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInsightsByAccountIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetInsightsByAccountIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetInsightsByAccountIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetInsightsByAccountIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetInsightsByAccountIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetInsightsByAccountIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetInsightsByAccountIDOK creates a GetInsightsByAccountIDOK with default headers values
func NewGetInsightsByAccountIDOK() *GetInsightsByAccountIDOK {
	return &GetInsightsByAccountIDOK{}
}

/*
GetInsightsByAccountIDOK describes a response with status code 200, with default header values.

Return matched Instagram Account insights.
*/
type GetInsightsByAccountIDOK struct {
	Payload *models.InstagramAccountInsights
}

// IsSuccess returns true when this get insights by account Id o k response has a 2xx status code
func (o *GetInsightsByAccountIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get insights by account Id o k response has a 3xx status code
func (o *GetInsightsByAccountIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get insights by account Id o k response has a 4xx status code
func (o *GetInsightsByAccountIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get insights by account Id o k response has a 5xx status code
func (o *GetInsightsByAccountIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get insights by account Id o k response a status code equal to that given
func (o *GetInsightsByAccountIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetInsightsByAccountIDOK) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/insights][%d] getInsightsByAccountIdOK  %+v", 200, o.Payload)
}

func (o *GetInsightsByAccountIDOK) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/insights][%d] getInsightsByAccountIdOK  %+v", 200, o.Payload)
}

func (o *GetInsightsByAccountIDOK) GetPayload() *models.InstagramAccountInsights {
	return o.Payload
}

func (o *GetInsightsByAccountIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InstagramAccountInsights)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInsightsByAccountIDBadRequest creates a GetInsightsByAccountIDBadRequest with default headers values
func NewGetInsightsByAccountIDBadRequest() *GetInsightsByAccountIDBadRequest {
	return &GetInsightsByAccountIDBadRequest{}
}

/*
GetInsightsByAccountIDBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetInsightsByAccountIDBadRequest struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get insights by account Id bad request response has a 2xx status code
func (o *GetInsightsByAccountIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get insights by account Id bad request response has a 3xx status code
func (o *GetInsightsByAccountIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get insights by account Id bad request response has a 4xx status code
func (o *GetInsightsByAccountIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get insights by account Id bad request response has a 5xx status code
func (o *GetInsightsByAccountIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get insights by account Id bad request response a status code equal to that given
func (o *GetInsightsByAccountIDBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetInsightsByAccountIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/insights][%d] getInsightsByAccountIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetInsightsByAccountIDBadRequest) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/insights][%d] getInsightsByAccountIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetInsightsByAccountIDBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetInsightsByAccountIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInsightsByAccountIDUnauthorized creates a GetInsightsByAccountIDUnauthorized with default headers values
func NewGetInsightsByAccountIDUnauthorized() *GetInsightsByAccountIDUnauthorized {
	return &GetInsightsByAccountIDUnauthorized{}
}

/*
GetInsightsByAccountIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetInsightsByAccountIDUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get insights by account Id unauthorized response has a 2xx status code
func (o *GetInsightsByAccountIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get insights by account Id unauthorized response has a 3xx status code
func (o *GetInsightsByAccountIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get insights by account Id unauthorized response has a 4xx status code
func (o *GetInsightsByAccountIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get insights by account Id unauthorized response has a 5xx status code
func (o *GetInsightsByAccountIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get insights by account Id unauthorized response a status code equal to that given
func (o *GetInsightsByAccountIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetInsightsByAccountIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/insights][%d] getInsightsByAccountIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetInsightsByAccountIDUnauthorized) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/insights][%d] getInsightsByAccountIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetInsightsByAccountIDUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetInsightsByAccountIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInsightsByAccountIDForbidden creates a GetInsightsByAccountIDForbidden with default headers values
func NewGetInsightsByAccountIDForbidden() *GetInsightsByAccountIDForbidden {
	return &GetInsightsByAccountIDForbidden{}
}

/*
GetInsightsByAccountIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetInsightsByAccountIDForbidden struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get insights by account Id forbidden response has a 2xx status code
func (o *GetInsightsByAccountIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get insights by account Id forbidden response has a 3xx status code
func (o *GetInsightsByAccountIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get insights by account Id forbidden response has a 4xx status code
func (o *GetInsightsByAccountIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get insights by account Id forbidden response has a 5xx status code
func (o *GetInsightsByAccountIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get insights by account Id forbidden response a status code equal to that given
func (o *GetInsightsByAccountIDForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetInsightsByAccountIDForbidden) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/insights][%d] getInsightsByAccountIdForbidden  %+v", 403, o.Payload)
}

func (o *GetInsightsByAccountIDForbidden) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/insights][%d] getInsightsByAccountIdForbidden  %+v", 403, o.Payload)
}

func (o *GetInsightsByAccountIDForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetInsightsByAccountIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInsightsByAccountIDNotFound creates a GetInsightsByAccountIDNotFound with default headers values
func NewGetInsightsByAccountIDNotFound() *GetInsightsByAccountIDNotFound {
	return &GetInsightsByAccountIDNotFound{}
}

/*
GetInsightsByAccountIDNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetInsightsByAccountIDNotFound struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get insights by account Id not found response has a 2xx status code
func (o *GetInsightsByAccountIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get insights by account Id not found response has a 3xx status code
func (o *GetInsightsByAccountIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get insights by account Id not found response has a 4xx status code
func (o *GetInsightsByAccountIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get insights by account Id not found response has a 5xx status code
func (o *GetInsightsByAccountIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get insights by account Id not found response a status code equal to that given
func (o *GetInsightsByAccountIDNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetInsightsByAccountIDNotFound) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/insights][%d] getInsightsByAccountIdNotFound  %+v", 404, o.Payload)
}

func (o *GetInsightsByAccountIDNotFound) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/insights][%d] getInsightsByAccountIdNotFound  %+v", 404, o.Payload)
}

func (o *GetInsightsByAccountIDNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetInsightsByAccountIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInsightsByAccountIDInternalServerError creates a GetInsightsByAccountIDInternalServerError with default headers values
func NewGetInsightsByAccountIDInternalServerError() *GetInsightsByAccountIDInternalServerError {
	return &GetInsightsByAccountIDInternalServerError{}
}

/*
GetInsightsByAccountIDInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetInsightsByAccountIDInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get insights by account Id internal server error response has a 2xx status code
func (o *GetInsightsByAccountIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get insights by account Id internal server error response has a 3xx status code
func (o *GetInsightsByAccountIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get insights by account Id internal server error response has a 4xx status code
func (o *GetInsightsByAccountIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get insights by account Id internal server error response has a 5xx status code
func (o *GetInsightsByAccountIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get insights by account Id internal server error response a status code equal to that given
func (o *GetInsightsByAccountIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetInsightsByAccountIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/insights][%d] getInsightsByAccountIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetInsightsByAccountIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/insights][%d] getInsightsByAccountIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetInsightsByAccountIDInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetInsightsByAccountIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
