// Code generated by go-swagger; DO NOT EDIT.

package insights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery -name API -inpkg

// API is the interface of the insights client
type API interface {
	/*
	   GetInsightsByAccountID gets insights data on an instagram account

	   Get insights data on your app user's Instagram business or creator account.

	   The following metrics have been deprecated for v22.0 and will be deprecated for all versions on April 21, 2025:
	   - impressions

	   Introducing the new views metric with total_value metric type and with breakdowns for follower_type and media_product_type.

	   Limitations:
	   - follower_count and online_followers metrics are not available on Instagram business or creator accounts with fewer than 100 followers.
	   - Insights data for the online_followers metric is only available for the last 30 days.
	   - If insights data you are requesting does not exist or is currently unavailable, the API returns an empty data set instead of 0 for individual metrics.
	   - Demographic metrics only return the top 45 performers.
	   - Only viewers for whom we have demographic data are used in demographic metric calculations.
	   - Summing demographic metric values may result in a value less than the follower count.
	   - Data used to calculate metrics may be delayed up to 48 hours.
	*/
	GetInsightsByAccountID(ctx context.Context, params *GetInsightsByAccountIDParams) (*GetInsightsByAccountIDOK, error)
}

// New creates a new insights API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for insights API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
GetInsightsByAccountID gets insights data on an instagram account

Get insights data on your app user's Instagram business or creator account.

The following metrics have been deprecated for v22.0 and will be deprecated for all versions on April 21, 2025:
- impressions

Introducing the new views metric with total_value metric type and with breakdowns for follower_type and media_product_type.

Limitations:
- follower_count and online_followers metrics are not available on Instagram business or creator accounts with fewer than 100 followers.
- Insights data for the online_followers metric is only available for the last 30 days.
- If insights data you are requesting does not exist or is currently unavailable, the API returns an empty data set instead of 0 for individual metrics.
- Demographic metrics only return the top 45 performers.
- Only viewers for whom we have demographic data are used in demographic metric calculations.
- Summing demographic metric values may result in a value less than the follower count.
- Data used to calculate metrics may be delayed up to 48 hours.
*/
func (a *Client) GetInsightsByAccountID(ctx context.Context, params *GetInsightsByAccountIDParams) (*GetInsightsByAccountIDOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetInsightsByAccountID",
		Method:             "GET",
		PathPattern:        "/{instagram_account_id}/insights",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetInsightsByAccountIDReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetInsightsByAccountIDOK), nil

}
