// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CommentData comment data
//
// swagger:model CommentData
type CommentData struct {

	// Comment ID
	ID string `json:"id,omitempty"`

	// Comment text
	Text string `json:"text,omitempty"`

	// ISO 8601 formatted timestamp of when the comment was created
	Timestamp string `json:"timestamp,omitempty"`
}

// Validate validates this comment data
func (m *CommentData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this comment data based on context it is used
func (m *CommentData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CommentData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CommentData) UnmarshalBinary(b []byte) error {
	var res CommentData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
