// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CommentCreated comment created
//
// swagger:model CommentCreated
type CommentCreated struct {

	// ID of the created comment
	ID string `json:"id,omitempty"`
}

// Validate validates this comment created
func (m *CommentCreated) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this comment created based on context it is used
func (m *CommentCreated) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CommentCreated) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CommentCreated) UnmarshalBinary(b []byte) error {
	var res CommentCreated
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
