// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InstagramMediaObject Instagram media object with requested fields
//
// swagger:model InstagramMediaObject
type InstagramMediaObject struct {

	// Descriptive text for images, for accessibility
	AltText string `json:"alt_text,omitempty"`

	// Caption text
	Caption string `json:"caption,omitempty"`

	// Count of comments on the media
	CommentsCount int64 `json:"comments_count,omitempty"`

	// Media ID
	ID string `json:"id,omitempty"`

	// Indicates if comments are enabled or disabled
	IsCommentEnabled bool `json:"is_comment_enabled,omitempty"`

	// For Reels only - indicates if reel can appear in Feed and Reels tabs
	IsSharedToFeed bool `json:"is_shared_to_feed,omitempty"`

	// ID for Instagram media created for Marketing API endpoints v21.0 and older
	LegacyInstagramMediaID string `json:"legacy_instagram_media_id,omitempty"`

	// Count of likes on the media
	LikeCount int64 `json:"like_count,omitempty"`

	// Surface where media is published (AD, FEED, STORY, REELS)
	// Enum: [AD FEED STORY REELS]
	MediaProductType string `json:"media_product_type,omitempty"`

	// Media type (CAROUSEL_ALBUM, IMAGE, or VIDEO)
	// Enum: [CAROUSEL_ALBUM IMAGE VIDEO]
	MediaType string `json:"media_type,omitempty"`

	// URL for the media
	MediaURL string `json:"media_url,omitempty"`

	// owner
	Owner *InstagramMediaObjectOwner `json:"owner,omitempty"`

	// Permanent URL to the media
	Permalink string `json:"permalink,omitempty"`

	// Shortcode to the media
	Shortcode string `json:"shortcode,omitempty"`

	// Media thumbnail URL (VIDEO media only)
	ThumbnailURL string `json:"thumbnail_url,omitempty"`

	// ISO 8601-formatted creation date in UTC
	Timestamp string `json:"timestamp,omitempty"`

	// Username of user who created the media
	Username string `json:"username,omitempty"`

	// View count for Instagram reels
	ViewCount int64 `json:"view_count,omitempty"`
}

// Validate validates this instagram media object
func (m *InstagramMediaObject) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMediaProductType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMediaType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOwner(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var instagramMediaObjectTypeMediaProductTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["AD","FEED","STORY","REELS"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		instagramMediaObjectTypeMediaProductTypePropEnum = append(instagramMediaObjectTypeMediaProductTypePropEnum, v)
	}
}

const (

	// InstagramMediaObjectMediaProductTypeAD captures enum value "AD"
	InstagramMediaObjectMediaProductTypeAD string = "AD"

	// InstagramMediaObjectMediaProductTypeFEED captures enum value "FEED"
	InstagramMediaObjectMediaProductTypeFEED string = "FEED"

	// InstagramMediaObjectMediaProductTypeSTORY captures enum value "STORY"
	InstagramMediaObjectMediaProductTypeSTORY string = "STORY"

	// InstagramMediaObjectMediaProductTypeREELS captures enum value "REELS"
	InstagramMediaObjectMediaProductTypeREELS string = "REELS"
)

// prop value enum
func (m *InstagramMediaObject) validateMediaProductTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, instagramMediaObjectTypeMediaProductTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *InstagramMediaObject) validateMediaProductType(formats strfmt.Registry) error {
	if swag.IsZero(m.MediaProductType) { // not required
		return nil
	}

	// value enum
	if err := m.validateMediaProductTypeEnum("media_product_type", "body", m.MediaProductType); err != nil {
		return err
	}

	return nil
}

var instagramMediaObjectTypeMediaTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["CAROUSEL_ALBUM","IMAGE","VIDEO"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		instagramMediaObjectTypeMediaTypePropEnum = append(instagramMediaObjectTypeMediaTypePropEnum, v)
	}
}

const (

	// InstagramMediaObjectMediaTypeCAROUSELALBUM captures enum value "CAROUSEL_ALBUM"
	InstagramMediaObjectMediaTypeCAROUSELALBUM string = "CAROUSEL_ALBUM"

	// InstagramMediaObjectMediaTypeIMAGE captures enum value "IMAGE"
	InstagramMediaObjectMediaTypeIMAGE string = "IMAGE"

	// InstagramMediaObjectMediaTypeVIDEO captures enum value "VIDEO"
	InstagramMediaObjectMediaTypeVIDEO string = "VIDEO"
)

// prop value enum
func (m *InstagramMediaObject) validateMediaTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, instagramMediaObjectTypeMediaTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *InstagramMediaObject) validateMediaType(formats strfmt.Registry) error {
	if swag.IsZero(m.MediaType) { // not required
		return nil
	}

	// value enum
	if err := m.validateMediaTypeEnum("media_type", "body", m.MediaType); err != nil {
		return err
	}

	return nil
}

func (m *InstagramMediaObject) validateOwner(formats strfmt.Registry) error {
	if swag.IsZero(m.Owner) { // not required
		return nil
	}

	if m.Owner != nil {
		if err := m.Owner.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("owner")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("owner")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this instagram media object based on the context it is used
func (m *InstagramMediaObject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOwner(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InstagramMediaObject) contextValidateOwner(ctx context.Context, formats strfmt.Registry) error {

	if m.Owner != nil {
		if err := m.Owner.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("owner")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("owner")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InstagramMediaObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InstagramMediaObject) UnmarshalBinary(b []byte) error {
	var res InstagramMediaObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// InstagramMediaObjectOwner Instagram user ID who created the media
//
// swagger:model InstagramMediaObjectOwner
type InstagramMediaObjectOwner struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this instagram media object owner
func (m *InstagramMediaObjectOwner) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this instagram media object owner based on context it is used
func (m *InstagramMediaObjectOwner) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InstagramMediaObjectOwner) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InstagramMediaObjectOwner) UnmarshalBinary(b []byte) error {
	var res InstagramMediaObjectOwner
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
