// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AccountInsightData account insight data
//
// swagger:model AccountInsightData
type AccountInsightData struct {

	// Metric description
	Description string `json:"description,omitempty"`

	// A string describing the query's path parameters
	ID string `json:"id,omitempty"`

	// Metric name
	Name string `json:"name,omitempty"`

	// Period requested (day or lifetime)
	Period string `json:"period,omitempty"`

	// Metric title
	Title string `json:"title,omitempty"`

	// total value
	TotalValue *AccountTotalValue `json:"total_value,omitempty"`

	// An array containing objects describing requested metric values (for time_series)
	Values []*AccountMetricValue `json:"values"`
}

// Validate validates this account insight data
func (m *AccountInsightData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTotalValue(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValues(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountInsightData) validateTotalValue(formats strfmt.Registry) error {
	if swag.IsZero(m.TotalValue) { // not required
		return nil
	}

	if m.TotalValue != nil {
		if err := m.TotalValue.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("total_value")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("total_value")
			}
			return err
		}
	}

	return nil
}

func (m *AccountInsightData) validateValues(formats strfmt.Registry) error {
	if swag.IsZero(m.Values) { // not required
		return nil
	}

	for i := 0; i < len(m.Values); i++ {
		if swag.IsZero(m.Values[i]) { // not required
			continue
		}

		if m.Values[i] != nil {
			if err := m.Values[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("values" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("values" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this account insight data based on the context it is used
func (m *AccountInsightData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTotalValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateValues(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountInsightData) contextValidateTotalValue(ctx context.Context, formats strfmt.Registry) error {

	if m.TotalValue != nil {
		if err := m.TotalValue.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("total_value")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("total_value")
			}
			return err
		}
	}

	return nil
}

func (m *AccountInsightData) contextValidateValues(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Values); i++ {

		if m.Values[i] != nil {
			if err := m.Values[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("values" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("values" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccountInsightData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountInsightData) UnmarshalBinary(b []byte) error {
	var res AccountInsightData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
