// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AccountMetricValue account metric value
//
// swagger:model AccountMetricValue
type AccountMetricValue struct {

	// ISO 8601 timestamp indicating end of the time period
	EndTime string `json:"end_time,omitempty"`

	// Metric value for the time period
	Value int64 `json:"value,omitempty"`
}

// Validate validates this account metric value
func (m *AccountMetricValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this account metric value based on context it is used
func (m *AccountMetricValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AccountMetricValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountMetricValue) UnmarshalBinary(b []byte) error {
	var res AccountMetricValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
