// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Paging An object containing URLs used to request the next set of results
//
// swagger:model Paging
type Paging struct {

	// URL to retrieve the next page of results
	Next string `json:"next,omitempty"`

	// URL to retrieve the previous page of results
	Previous string `json:"previous,omitempty"`
}

// Validate validates this paging
func (m *Paging) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this paging based on context it is used
func (m *Paging) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Paging) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Paging) UnmarshalBinary(b []byte) error {
	var res Paging
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
