// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TotalValue Object describing requested breakdown values (if breakdowns were requested)
//
// swagger:model TotalValue
type TotalValue struct {

	// An array of objects describing the breakdowns requested and their results
	Breakdowns []*Breakdown `json:"breakdowns"`

	// Sum of requested breakdown values
	Value int64 `json:"value,omitempty"`
}

// Validate validates this total value
func (m *TotalValue) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBreakdowns(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TotalValue) validateBreakdowns(formats strfmt.Registry) error {
	if swag.IsZero(m.Breakdowns) { // not required
		return nil
	}

	for i := 0; i < len(m.Breakdowns); i++ {
		if swag.IsZero(m.Breakdowns[i]) { // not required
			continue
		}

		if m.Breakdowns[i] != nil {
			if err := m.Breakdowns[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("breakdowns" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("breakdowns" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this total value based on the context it is used
func (m *TotalValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBreakdowns(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TotalValue) contextValidateBreakdowns(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Breakdowns); i++ {

		if m.Breakdowns[i] != nil {
			if err := m.Breakdowns[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("breakdowns" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("breakdowns" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TotalValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TotalValue) UnmarshalBinary(b []byte) error {
	var res TotalValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
