// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qcserestipy/instagram-api-go-client/pkg/sdk/v24.0/account/models"
)

// CreateMediaContainerReader is a Reader for the CreateMediaContainer structure.
type CreateMediaContainerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateMediaContainerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateMediaContainerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateMediaContainerBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateMediaContainerUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateMediaContainerForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateMediaContainerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateMediaContainerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateMediaContainerOK creates a CreateMediaContainerOK with default headers values
func NewCreateMediaContainerOK() *CreateMediaContainerOK {
	return &CreateMediaContainerOK{}
}

/*
CreateMediaContainerOK describes a response with status code 200, with default header values.

Container created successfully.
*/
type CreateMediaContainerOK struct {
	Payload *models.MediaContainerCreated
}

// IsSuccess returns true when this create media container o k response has a 2xx status code
func (o *CreateMediaContainerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create media container o k response has a 3xx status code
func (o *CreateMediaContainerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create media container o k response has a 4xx status code
func (o *CreateMediaContainerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create media container o k response has a 5xx status code
func (o *CreateMediaContainerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create media container o k response a status code equal to that given
func (o *CreateMediaContainerOK) IsCode(code int) bool {
	return code == 200
}

func (o *CreateMediaContainerOK) Error() string {
	return fmt.Sprintf("[POST /{instagram_account_id}/media][%d] createMediaContainerOK  %+v", 200, o.Payload)
}

func (o *CreateMediaContainerOK) String() string {
	return fmt.Sprintf("[POST /{instagram_account_id}/media][%d] createMediaContainerOK  %+v", 200, o.Payload)
}

func (o *CreateMediaContainerOK) GetPayload() *models.MediaContainerCreated {
	return o.Payload
}

func (o *CreateMediaContainerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MediaContainerCreated)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateMediaContainerBadRequest creates a CreateMediaContainerBadRequest with default headers values
func NewCreateMediaContainerBadRequest() *CreateMediaContainerBadRequest {
	return &CreateMediaContainerBadRequest{}
}

/*
CreateMediaContainerBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type CreateMediaContainerBadRequest struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this create media container bad request response has a 2xx status code
func (o *CreateMediaContainerBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create media container bad request response has a 3xx status code
func (o *CreateMediaContainerBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create media container bad request response has a 4xx status code
func (o *CreateMediaContainerBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create media container bad request response has a 5xx status code
func (o *CreateMediaContainerBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create media container bad request response a status code equal to that given
func (o *CreateMediaContainerBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CreateMediaContainerBadRequest) Error() string {
	return fmt.Sprintf("[POST /{instagram_account_id}/media][%d] createMediaContainerBadRequest  %+v", 400, o.Payload)
}

func (o *CreateMediaContainerBadRequest) String() string {
	return fmt.Sprintf("[POST /{instagram_account_id}/media][%d] createMediaContainerBadRequest  %+v", 400, o.Payload)
}

func (o *CreateMediaContainerBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *CreateMediaContainerBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateMediaContainerUnauthorized creates a CreateMediaContainerUnauthorized with default headers values
func NewCreateMediaContainerUnauthorized() *CreateMediaContainerUnauthorized {
	return &CreateMediaContainerUnauthorized{}
}

/*
CreateMediaContainerUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateMediaContainerUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this create media container unauthorized response has a 2xx status code
func (o *CreateMediaContainerUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create media container unauthorized response has a 3xx status code
func (o *CreateMediaContainerUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create media container unauthorized response has a 4xx status code
func (o *CreateMediaContainerUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create media container unauthorized response has a 5xx status code
func (o *CreateMediaContainerUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create media container unauthorized response a status code equal to that given
func (o *CreateMediaContainerUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateMediaContainerUnauthorized) Error() string {
	return fmt.Sprintf("[POST /{instagram_account_id}/media][%d] createMediaContainerUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateMediaContainerUnauthorized) String() string {
	return fmt.Sprintf("[POST /{instagram_account_id}/media][%d] createMediaContainerUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateMediaContainerUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *CreateMediaContainerUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateMediaContainerForbidden creates a CreateMediaContainerForbidden with default headers values
func NewCreateMediaContainerForbidden() *CreateMediaContainerForbidden {
	return &CreateMediaContainerForbidden{}
}

/*
CreateMediaContainerForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateMediaContainerForbidden struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this create media container forbidden response has a 2xx status code
func (o *CreateMediaContainerForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create media container forbidden response has a 3xx status code
func (o *CreateMediaContainerForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create media container forbidden response has a 4xx status code
func (o *CreateMediaContainerForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create media container forbidden response has a 5xx status code
func (o *CreateMediaContainerForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create media container forbidden response a status code equal to that given
func (o *CreateMediaContainerForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateMediaContainerForbidden) Error() string {
	return fmt.Sprintf("[POST /{instagram_account_id}/media][%d] createMediaContainerForbidden  %+v", 403, o.Payload)
}

func (o *CreateMediaContainerForbidden) String() string {
	return fmt.Sprintf("[POST /{instagram_account_id}/media][%d] createMediaContainerForbidden  %+v", 403, o.Payload)
}

func (o *CreateMediaContainerForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *CreateMediaContainerForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateMediaContainerNotFound creates a CreateMediaContainerNotFound with default headers values
func NewCreateMediaContainerNotFound() *CreateMediaContainerNotFound {
	return &CreateMediaContainerNotFound{}
}

/*
CreateMediaContainerNotFound describes a response with status code 404, with default header values.

Not found
*/
type CreateMediaContainerNotFound struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this create media container not found response has a 2xx status code
func (o *CreateMediaContainerNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create media container not found response has a 3xx status code
func (o *CreateMediaContainerNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create media container not found response has a 4xx status code
func (o *CreateMediaContainerNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create media container not found response has a 5xx status code
func (o *CreateMediaContainerNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create media container not found response a status code equal to that given
func (o *CreateMediaContainerNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *CreateMediaContainerNotFound) Error() string {
	return fmt.Sprintf("[POST /{instagram_account_id}/media][%d] createMediaContainerNotFound  %+v", 404, o.Payload)
}

func (o *CreateMediaContainerNotFound) String() string {
	return fmt.Sprintf("[POST /{instagram_account_id}/media][%d] createMediaContainerNotFound  %+v", 404, o.Payload)
}

func (o *CreateMediaContainerNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *CreateMediaContainerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateMediaContainerInternalServerError creates a CreateMediaContainerInternalServerError with default headers values
func NewCreateMediaContainerInternalServerError() *CreateMediaContainerInternalServerError {
	return &CreateMediaContainerInternalServerError{}
}

/*
CreateMediaContainerInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type CreateMediaContainerInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this create media container internal server error response has a 2xx status code
func (o *CreateMediaContainerInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create media container internal server error response has a 3xx status code
func (o *CreateMediaContainerInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create media container internal server error response has a 4xx status code
func (o *CreateMediaContainerInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create media container internal server error response has a 5xx status code
func (o *CreateMediaContainerInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create media container internal server error response a status code equal to that given
func (o *CreateMediaContainerInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *CreateMediaContainerInternalServerError) Error() string {
	return fmt.Sprintf("[POST /{instagram_account_id}/media][%d] createMediaContainerInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateMediaContainerInternalServerError) String() string {
	return fmt.Sprintf("[POST /{instagram_account_id}/media][%d] createMediaContainerInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateMediaContainerInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *CreateMediaContainerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
