// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCreateMediaContainerParams creates a new CreateMediaContainerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateMediaContainerParams() *CreateMediaContainerParams {
	return &CreateMediaContainerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateMediaContainerParamsWithTimeout creates a new CreateMediaContainerParams object
// with the ability to set a timeout on a request.
func NewCreateMediaContainerParamsWithTimeout(timeout time.Duration) *CreateMediaContainerParams {
	return &CreateMediaContainerParams{
		timeout: timeout,
	}
}

// NewCreateMediaContainerParamsWithContext creates a new CreateMediaContainerParams object
// with the ability to set a context for a request.
func NewCreateMediaContainerParamsWithContext(ctx context.Context) *CreateMediaContainerParams {
	return &CreateMediaContainerParams{
		Context: ctx,
	}
}

// NewCreateMediaContainerParamsWithHTTPClient creates a new CreateMediaContainerParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateMediaContainerParamsWithHTTPClient(client *http.Client) *CreateMediaContainerParams {
	return &CreateMediaContainerParams{
		HTTPClient: client,
	}
}

/*
CreateMediaContainerParams contains all the parameters to send to the API endpoint

	for the create media container operation.

	Typically these are written to a http.Request.
*/
type CreateMediaContainerParams struct {

	/* XRequestID.

	   An unique ID for the request
	*/
	XRequestID *string

	/* AltText.

	   For image posts only. Alternative text, up to 1000 characters. Only supported on single images or images in a carousel. Reels and stories not supported.
	*/
	AltText *string

	/* AudioName.

	   For Reels only. Name of the audio of your Reels media.
	*/
	AudioName *string

	/* Caption.

	   A caption for the image, video, or carousel. Maximum 2200 characters, 30 hashtags, and 20 @ tags. Not supported on images or videos in carousels.
	*/
	Caption *string

	/* Children.

	   Required for carousels. Array of up to 10 container IDs for carousel items.
	*/
	Children *string

	/* Collaborators.

	   For Feed images, Reels, and Carousels only. List of up to 3 Instagram usernames as collaborators. Format ["username1","username2"]
	*/
	Collaborators *string

	/* CoverURL.

	   For Reels only. Path to an image to use as the cover image for the Reels tab.
	*/
	CoverURL *string

	/* ImageURL.

	   Required for images. The path to the image. We will cURL the image using the URL that you specify so the image must be on a public server.
	*/
	ImageURL *string

	/* InstagramAccountID.

	   Instagram Account ID (your app user's Instagram professional account ID)
	*/
	InstagramAccountID string

	/* IsCarouselItem.

	   Applies only to images and videos. Set to true to indicate image or video appears in a carousel.
	*/
	IsCarouselItem *bool

	/* LocationID.

	   The ID of a Page associated with a location to tag the media with. Not supported on images or videos in carousels.
	*/
	LocationID *string

	/* MediaType.

	     Required for carousels, stories, and reels. Indicates container is for a carousel, story or reel. Values:
	- CAROUSEL
	- REELS
	- STORIES

	*/
	MediaType *string

	/* ProductTags.

	   Array of product tags (max 5). Format: [{"product_id":"123","x":0.5,"y":0.8}]

	*/
	ProductTags *string

	/* ShareToFeed.

	   For Reels only. When true, reel can appear in both Feed and Reels tabs. When false, only in Reels tab.
	*/
	ShareToFeed *bool

	/* ThumbOffset.

	   For videos and reels. Location in milliseconds of the frame to be used as cover thumbnail. Default is 0.
	*/
	ThumbOffset *int64

	/* UploadType.

	   Set to "resumable" for resumable upload protocol.
	*/
	UploadType *string

	/* UserTags.

	   Array of public usernames and x/y coordinates for tagging Instagram users. Format: [{"username":"user1","x":0.5,"y":0.8}]

	*/
	UserTags *string

	/* VideoURL.

	   Required for videos and reels. Path to the video. We cURL the video using the passed-in URL, so it must be on a public server.
	*/
	VideoURL *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create media container params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMediaContainerParams) WithDefaults() *CreateMediaContainerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create media container params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMediaContainerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create media container params
func (o *CreateMediaContainerParams) WithTimeout(timeout time.Duration) *CreateMediaContainerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create media container params
func (o *CreateMediaContainerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create media container params
func (o *CreateMediaContainerParams) WithContext(ctx context.Context) *CreateMediaContainerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create media container params
func (o *CreateMediaContainerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create media container params
func (o *CreateMediaContainerParams) WithHTTPClient(client *http.Client) *CreateMediaContainerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create media container params
func (o *CreateMediaContainerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the create media container params
func (o *CreateMediaContainerParams) WithXRequestID(xRequestID *string) *CreateMediaContainerParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the create media container params
func (o *CreateMediaContainerParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithAltText adds the altText to the create media container params
func (o *CreateMediaContainerParams) WithAltText(altText *string) *CreateMediaContainerParams {
	o.SetAltText(altText)
	return o
}

// SetAltText adds the altText to the create media container params
func (o *CreateMediaContainerParams) SetAltText(altText *string) {
	o.AltText = altText
}

// WithAudioName adds the audioName to the create media container params
func (o *CreateMediaContainerParams) WithAudioName(audioName *string) *CreateMediaContainerParams {
	o.SetAudioName(audioName)
	return o
}

// SetAudioName adds the audioName to the create media container params
func (o *CreateMediaContainerParams) SetAudioName(audioName *string) {
	o.AudioName = audioName
}

// WithCaption adds the caption to the create media container params
func (o *CreateMediaContainerParams) WithCaption(caption *string) *CreateMediaContainerParams {
	o.SetCaption(caption)
	return o
}

// SetCaption adds the caption to the create media container params
func (o *CreateMediaContainerParams) SetCaption(caption *string) {
	o.Caption = caption
}

// WithChildren adds the children to the create media container params
func (o *CreateMediaContainerParams) WithChildren(children *string) *CreateMediaContainerParams {
	o.SetChildren(children)
	return o
}

// SetChildren adds the children to the create media container params
func (o *CreateMediaContainerParams) SetChildren(children *string) {
	o.Children = children
}

// WithCollaborators adds the collaborators to the create media container params
func (o *CreateMediaContainerParams) WithCollaborators(collaborators *string) *CreateMediaContainerParams {
	o.SetCollaborators(collaborators)
	return o
}

// SetCollaborators adds the collaborators to the create media container params
func (o *CreateMediaContainerParams) SetCollaborators(collaborators *string) {
	o.Collaborators = collaborators
}

// WithCoverURL adds the coverURL to the create media container params
func (o *CreateMediaContainerParams) WithCoverURL(coverURL *string) *CreateMediaContainerParams {
	o.SetCoverURL(coverURL)
	return o
}

// SetCoverURL adds the coverUrl to the create media container params
func (o *CreateMediaContainerParams) SetCoverURL(coverURL *string) {
	o.CoverURL = coverURL
}

// WithImageURL adds the imageURL to the create media container params
func (o *CreateMediaContainerParams) WithImageURL(imageURL *string) *CreateMediaContainerParams {
	o.SetImageURL(imageURL)
	return o
}

// SetImageURL adds the imageUrl to the create media container params
func (o *CreateMediaContainerParams) SetImageURL(imageURL *string) {
	o.ImageURL = imageURL
}

// WithInstagramAccountID adds the instagramAccountID to the create media container params
func (o *CreateMediaContainerParams) WithInstagramAccountID(instagramAccountID string) *CreateMediaContainerParams {
	o.SetInstagramAccountID(instagramAccountID)
	return o
}

// SetInstagramAccountID adds the instagramAccountId to the create media container params
func (o *CreateMediaContainerParams) SetInstagramAccountID(instagramAccountID string) {
	o.InstagramAccountID = instagramAccountID
}

// WithIsCarouselItem adds the isCarouselItem to the create media container params
func (o *CreateMediaContainerParams) WithIsCarouselItem(isCarouselItem *bool) *CreateMediaContainerParams {
	o.SetIsCarouselItem(isCarouselItem)
	return o
}

// SetIsCarouselItem adds the isCarouselItem to the create media container params
func (o *CreateMediaContainerParams) SetIsCarouselItem(isCarouselItem *bool) {
	o.IsCarouselItem = isCarouselItem
}

// WithLocationID adds the locationID to the create media container params
func (o *CreateMediaContainerParams) WithLocationID(locationID *string) *CreateMediaContainerParams {
	o.SetLocationID(locationID)
	return o
}

// SetLocationID adds the locationId to the create media container params
func (o *CreateMediaContainerParams) SetLocationID(locationID *string) {
	o.LocationID = locationID
}

// WithMediaType adds the mediaType to the create media container params
func (o *CreateMediaContainerParams) WithMediaType(mediaType *string) *CreateMediaContainerParams {
	o.SetMediaType(mediaType)
	return o
}

// SetMediaType adds the mediaType to the create media container params
func (o *CreateMediaContainerParams) SetMediaType(mediaType *string) {
	o.MediaType = mediaType
}

// WithProductTags adds the productTags to the create media container params
func (o *CreateMediaContainerParams) WithProductTags(productTags *string) *CreateMediaContainerParams {
	o.SetProductTags(productTags)
	return o
}

// SetProductTags adds the productTags to the create media container params
func (o *CreateMediaContainerParams) SetProductTags(productTags *string) {
	o.ProductTags = productTags
}

// WithShareToFeed adds the shareToFeed to the create media container params
func (o *CreateMediaContainerParams) WithShareToFeed(shareToFeed *bool) *CreateMediaContainerParams {
	o.SetShareToFeed(shareToFeed)
	return o
}

// SetShareToFeed adds the shareToFeed to the create media container params
func (o *CreateMediaContainerParams) SetShareToFeed(shareToFeed *bool) {
	o.ShareToFeed = shareToFeed
}

// WithThumbOffset adds the thumbOffset to the create media container params
func (o *CreateMediaContainerParams) WithThumbOffset(thumbOffset *int64) *CreateMediaContainerParams {
	o.SetThumbOffset(thumbOffset)
	return o
}

// SetThumbOffset adds the thumbOffset to the create media container params
func (o *CreateMediaContainerParams) SetThumbOffset(thumbOffset *int64) {
	o.ThumbOffset = thumbOffset
}

// WithUploadType adds the uploadType to the create media container params
func (o *CreateMediaContainerParams) WithUploadType(uploadType *string) *CreateMediaContainerParams {
	o.SetUploadType(uploadType)
	return o
}

// SetUploadType adds the uploadType to the create media container params
func (o *CreateMediaContainerParams) SetUploadType(uploadType *string) {
	o.UploadType = uploadType
}

// WithUserTags adds the userTags to the create media container params
func (o *CreateMediaContainerParams) WithUserTags(userTags *string) *CreateMediaContainerParams {
	o.SetUserTags(userTags)
	return o
}

// SetUserTags adds the userTags to the create media container params
func (o *CreateMediaContainerParams) SetUserTags(userTags *string) {
	o.UserTags = userTags
}

// WithVideoURL adds the videoURL to the create media container params
func (o *CreateMediaContainerParams) WithVideoURL(videoURL *string) *CreateMediaContainerParams {
	o.SetVideoURL(videoURL)
	return o
}

// SetVideoURL adds the videoUrl to the create media container params
func (o *CreateMediaContainerParams) SetVideoURL(videoURL *string) {
	o.VideoURL = videoURL
}

// WriteToRequest writes these params to a swagger request
func (o *CreateMediaContainerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	if o.AltText != nil {

		// query param alt_text
		var qrAltText string

		if o.AltText != nil {
			qrAltText = *o.AltText
		}
		qAltText := qrAltText
		if qAltText != "" {

			if err := r.SetQueryParam("alt_text", qAltText); err != nil {
				return err
			}
		}
	}

	if o.AudioName != nil {

		// query param audio_name
		var qrAudioName string

		if o.AudioName != nil {
			qrAudioName = *o.AudioName
		}
		qAudioName := qrAudioName
		if qAudioName != "" {

			if err := r.SetQueryParam("audio_name", qAudioName); err != nil {
				return err
			}
		}
	}

	if o.Caption != nil {

		// query param caption
		var qrCaption string

		if o.Caption != nil {
			qrCaption = *o.Caption
		}
		qCaption := qrCaption
		if qCaption != "" {

			if err := r.SetQueryParam("caption", qCaption); err != nil {
				return err
			}
		}
	}

	if o.Children != nil {

		// query param children
		var qrChildren string

		if o.Children != nil {
			qrChildren = *o.Children
		}
		qChildren := qrChildren
		if qChildren != "" {

			if err := r.SetQueryParam("children", qChildren); err != nil {
				return err
			}
		}
	}

	if o.Collaborators != nil {

		// query param collaborators
		var qrCollaborators string

		if o.Collaborators != nil {
			qrCollaborators = *o.Collaborators
		}
		qCollaborators := qrCollaborators
		if qCollaborators != "" {

			if err := r.SetQueryParam("collaborators", qCollaborators); err != nil {
				return err
			}
		}
	}

	if o.CoverURL != nil {

		// query param cover_url
		var qrCoverURL string

		if o.CoverURL != nil {
			qrCoverURL = *o.CoverURL
		}
		qCoverURL := qrCoverURL
		if qCoverURL != "" {

			if err := r.SetQueryParam("cover_url", qCoverURL); err != nil {
				return err
			}
		}
	}

	if o.ImageURL != nil {

		// query param image_url
		var qrImageURL string

		if o.ImageURL != nil {
			qrImageURL = *o.ImageURL
		}
		qImageURL := qrImageURL
		if qImageURL != "" {

			if err := r.SetQueryParam("image_url", qImageURL); err != nil {
				return err
			}
		}
	}

	// path param instagram_account_id
	if err := r.SetPathParam("instagram_account_id", o.InstagramAccountID); err != nil {
		return err
	}

	if o.IsCarouselItem != nil {

		// query param is_carousel_item
		var qrIsCarouselItem bool

		if o.IsCarouselItem != nil {
			qrIsCarouselItem = *o.IsCarouselItem
		}
		qIsCarouselItem := swag.FormatBool(qrIsCarouselItem)
		if qIsCarouselItem != "" {

			if err := r.SetQueryParam("is_carousel_item", qIsCarouselItem); err != nil {
				return err
			}
		}
	}

	if o.LocationID != nil {

		// query param location_id
		var qrLocationID string

		if o.LocationID != nil {
			qrLocationID = *o.LocationID
		}
		qLocationID := qrLocationID
		if qLocationID != "" {

			if err := r.SetQueryParam("location_id", qLocationID); err != nil {
				return err
			}
		}
	}

	if o.MediaType != nil {

		// query param media_type
		var qrMediaType string

		if o.MediaType != nil {
			qrMediaType = *o.MediaType
		}
		qMediaType := qrMediaType
		if qMediaType != "" {

			if err := r.SetQueryParam("media_type", qMediaType); err != nil {
				return err
			}
		}
	}

	if o.ProductTags != nil {

		// query param product_tags
		var qrProductTags string

		if o.ProductTags != nil {
			qrProductTags = *o.ProductTags
		}
		qProductTags := qrProductTags
		if qProductTags != "" {

			if err := r.SetQueryParam("product_tags", qProductTags); err != nil {
				return err
			}
		}
	}

	if o.ShareToFeed != nil {

		// query param share_to_feed
		var qrShareToFeed bool

		if o.ShareToFeed != nil {
			qrShareToFeed = *o.ShareToFeed
		}
		qShareToFeed := swag.FormatBool(qrShareToFeed)
		if qShareToFeed != "" {

			if err := r.SetQueryParam("share_to_feed", qShareToFeed); err != nil {
				return err
			}
		}
	}

	if o.ThumbOffset != nil {

		// query param thumb_offset
		var qrThumbOffset int64

		if o.ThumbOffset != nil {
			qrThumbOffset = *o.ThumbOffset
		}
		qThumbOffset := swag.FormatInt64(qrThumbOffset)
		if qThumbOffset != "" {

			if err := r.SetQueryParam("thumb_offset", qThumbOffset); err != nil {
				return err
			}
		}
	}

	if o.UploadType != nil {

		// query param upload_type
		var qrUploadType string

		if o.UploadType != nil {
			qrUploadType = *o.UploadType
		}
		qUploadType := qrUploadType
		if qUploadType != "" {

			if err := r.SetQueryParam("upload_type", qUploadType); err != nil {
				return err
			}
		}
	}

	if o.UserTags != nil {

		// query param user_tags
		var qrUserTags string

		if o.UserTags != nil {
			qrUserTags = *o.UserTags
		}
		qUserTags := qrUserTags
		if qUserTags != "" {

			if err := r.SetQueryParam("user_tags", qUserTags); err != nil {
				return err
			}
		}
	}

	if o.VideoURL != nil {

		// query param video_url
		var qrVideoURL string

		if o.VideoURL != nil {
			qrVideoURL = *o.VideoURL
		}
		qVideoURL := qrVideoURL
		if qVideoURL != "" {

			if err := r.SetQueryParam("video_url", qVideoURL); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
