// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetMediaByUserIDParams creates a new GetMediaByUserIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMediaByUserIDParams() *GetMediaByUserIDParams {
	return &GetMediaByUserIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMediaByUserIDParamsWithTimeout creates a new GetMediaByUserIDParams object
// with the ability to set a timeout on a request.
func NewGetMediaByUserIDParamsWithTimeout(timeout time.Duration) *GetMediaByUserIDParams {
	return &GetMediaByUserIDParams{
		timeout: timeout,
	}
}

// NewGetMediaByUserIDParamsWithContext creates a new GetMediaByUserIDParams object
// with the ability to set a context for a request.
func NewGetMediaByUserIDParamsWithContext(ctx context.Context) *GetMediaByUserIDParams {
	return &GetMediaByUserIDParams{
		Context: ctx,
	}
}

// NewGetMediaByUserIDParamsWithHTTPClient creates a new GetMediaByUserIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMediaByUserIDParamsWithHTTPClient(client *http.Client) *GetMediaByUserIDParams {
	return &GetMediaByUserIDParams{
		HTTPClient: client,
	}
}

/*
GetMediaByUserIDParams contains all the parameters to send to the API endpoint

	for the get media by user ID operation.

	Typically these are written to a http.Request.
*/
type GetMediaByUserIDParams struct {

	/* XRequestID.

	   An unique ID for the request
	*/
	XRequestID *string

	/* InstagramAccountID.

	   Instagram Account ID (your app user's Instagram professional account ID)
	*/
	InstagramAccountID string

	/* Since.

	   Unix timestamp indicating start of range. The API will only include data created within this range (inclusive). If not included, API looks back 24 hours.

	   Format: int64
	*/
	Since *int64

	/* Until.

	   Unix timestamp indicating end of range. The API will only include data created within this range (inclusive). If not included, API looks back 24 hours.

	   Format: int64
	*/
	Until *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get media by user ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMediaByUserIDParams) WithDefaults() *GetMediaByUserIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get media by user ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMediaByUserIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get media by user ID params
func (o *GetMediaByUserIDParams) WithTimeout(timeout time.Duration) *GetMediaByUserIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get media by user ID params
func (o *GetMediaByUserIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get media by user ID params
func (o *GetMediaByUserIDParams) WithContext(ctx context.Context) *GetMediaByUserIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get media by user ID params
func (o *GetMediaByUserIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get media by user ID params
func (o *GetMediaByUserIDParams) WithHTTPClient(client *http.Client) *GetMediaByUserIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get media by user ID params
func (o *GetMediaByUserIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the get media by user ID params
func (o *GetMediaByUserIDParams) WithXRequestID(xRequestID *string) *GetMediaByUserIDParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the get media by user ID params
func (o *GetMediaByUserIDParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithInstagramAccountID adds the instagramAccountID to the get media by user ID params
func (o *GetMediaByUserIDParams) WithInstagramAccountID(instagramAccountID string) *GetMediaByUserIDParams {
	o.SetInstagramAccountID(instagramAccountID)
	return o
}

// SetInstagramAccountID adds the instagramAccountId to the get media by user ID params
func (o *GetMediaByUserIDParams) SetInstagramAccountID(instagramAccountID string) {
	o.InstagramAccountID = instagramAccountID
}

// WithSince adds the since to the get media by user ID params
func (o *GetMediaByUserIDParams) WithSince(since *int64) *GetMediaByUserIDParams {
	o.SetSince(since)
	return o
}

// SetSince adds the since to the get media by user ID params
func (o *GetMediaByUserIDParams) SetSince(since *int64) {
	o.Since = since
}

// WithUntil adds the until to the get media by user ID params
func (o *GetMediaByUserIDParams) WithUntil(until *int64) *GetMediaByUserIDParams {
	o.SetUntil(until)
	return o
}

// SetUntil adds the until to the get media by user ID params
func (o *GetMediaByUserIDParams) SetUntil(until *int64) {
	o.Until = until
}

// WriteToRequest writes these params to a swagger request
func (o *GetMediaByUserIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	// path param instagram_account_id
	if err := r.SetPathParam("instagram_account_id", o.InstagramAccountID); err != nil {
		return err
	}

	if o.Since != nil {

		// query param since
		var qrSince int64

		if o.Since != nil {
			qrSince = *o.Since
		}
		qSince := swag.FormatInt64(qrSince)
		if qSince != "" {

			if err := r.SetQueryParam("since", qSince); err != nil {
				return err
			}
		}
	}

	if o.Until != nil {

		// query param until
		var qrUntil int64

		if o.Until != nil {
			qrUntil = *o.Until
		}
		qUntil := swag.FormatInt64(qrUntil)
		if qUntil != "" {

			if err := r.SetQueryParam("until", qUntil); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
