// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qcserestipy/instagram-api-go-client/pkg/sdk/v24.0/account/models"
)

// GetMediaByUserIDReader is a Reader for the GetMediaByUserID structure.
type GetMediaByUserIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMediaByUserIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMediaByUserIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetMediaByUserIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetMediaByUserIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetMediaByUserIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetMediaByUserIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetMediaByUserIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetMediaByUserIDOK creates a GetMediaByUserIDOK with default headers values
func NewGetMediaByUserIDOK() *GetMediaByUserIDOK {
	return &GetMediaByUserIDOK{}
}

/*
GetMediaByUserIDOK describes a response with status code 200, with default header values.

Return list of media objects.
*/
type GetMediaByUserIDOK struct {
	Payload *models.InstagramMedia
}

// IsSuccess returns true when this get media by user Id o k response has a 2xx status code
func (o *GetMediaByUserIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get media by user Id o k response has a 3xx status code
func (o *GetMediaByUserIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get media by user Id o k response has a 4xx status code
func (o *GetMediaByUserIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get media by user Id o k response has a 5xx status code
func (o *GetMediaByUserIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get media by user Id o k response a status code equal to that given
func (o *GetMediaByUserIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetMediaByUserIDOK) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/media][%d] getMediaByUserIdOK  %+v", 200, o.Payload)
}

func (o *GetMediaByUserIDOK) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/media][%d] getMediaByUserIdOK  %+v", 200, o.Payload)
}

func (o *GetMediaByUserIDOK) GetPayload() *models.InstagramMedia {
	return o.Payload
}

func (o *GetMediaByUserIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InstagramMedia)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMediaByUserIDBadRequest creates a GetMediaByUserIDBadRequest with default headers values
func NewGetMediaByUserIDBadRequest() *GetMediaByUserIDBadRequest {
	return &GetMediaByUserIDBadRequest{}
}

/*
GetMediaByUserIDBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetMediaByUserIDBadRequest struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get media by user Id bad request response has a 2xx status code
func (o *GetMediaByUserIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get media by user Id bad request response has a 3xx status code
func (o *GetMediaByUserIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get media by user Id bad request response has a 4xx status code
func (o *GetMediaByUserIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get media by user Id bad request response has a 5xx status code
func (o *GetMediaByUserIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get media by user Id bad request response a status code equal to that given
func (o *GetMediaByUserIDBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetMediaByUserIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/media][%d] getMediaByUserIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetMediaByUserIDBadRequest) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/media][%d] getMediaByUserIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetMediaByUserIDBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetMediaByUserIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMediaByUserIDUnauthorized creates a GetMediaByUserIDUnauthorized with default headers values
func NewGetMediaByUserIDUnauthorized() *GetMediaByUserIDUnauthorized {
	return &GetMediaByUserIDUnauthorized{}
}

/*
GetMediaByUserIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetMediaByUserIDUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get media by user Id unauthorized response has a 2xx status code
func (o *GetMediaByUserIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get media by user Id unauthorized response has a 3xx status code
func (o *GetMediaByUserIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get media by user Id unauthorized response has a 4xx status code
func (o *GetMediaByUserIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get media by user Id unauthorized response has a 5xx status code
func (o *GetMediaByUserIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get media by user Id unauthorized response a status code equal to that given
func (o *GetMediaByUserIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetMediaByUserIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/media][%d] getMediaByUserIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetMediaByUserIDUnauthorized) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/media][%d] getMediaByUserIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetMediaByUserIDUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetMediaByUserIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMediaByUserIDForbidden creates a GetMediaByUserIDForbidden with default headers values
func NewGetMediaByUserIDForbidden() *GetMediaByUserIDForbidden {
	return &GetMediaByUserIDForbidden{}
}

/*
GetMediaByUserIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetMediaByUserIDForbidden struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get media by user Id forbidden response has a 2xx status code
func (o *GetMediaByUserIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get media by user Id forbidden response has a 3xx status code
func (o *GetMediaByUserIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get media by user Id forbidden response has a 4xx status code
func (o *GetMediaByUserIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get media by user Id forbidden response has a 5xx status code
func (o *GetMediaByUserIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get media by user Id forbidden response a status code equal to that given
func (o *GetMediaByUserIDForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetMediaByUserIDForbidden) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/media][%d] getMediaByUserIdForbidden  %+v", 403, o.Payload)
}

func (o *GetMediaByUserIDForbidden) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/media][%d] getMediaByUserIdForbidden  %+v", 403, o.Payload)
}

func (o *GetMediaByUserIDForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetMediaByUserIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMediaByUserIDNotFound creates a GetMediaByUserIDNotFound with default headers values
func NewGetMediaByUserIDNotFound() *GetMediaByUserIDNotFound {
	return &GetMediaByUserIDNotFound{}
}

/*
GetMediaByUserIDNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetMediaByUserIDNotFound struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get media by user Id not found response has a 2xx status code
func (o *GetMediaByUserIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get media by user Id not found response has a 3xx status code
func (o *GetMediaByUserIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get media by user Id not found response has a 4xx status code
func (o *GetMediaByUserIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get media by user Id not found response has a 5xx status code
func (o *GetMediaByUserIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get media by user Id not found response a status code equal to that given
func (o *GetMediaByUserIDNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetMediaByUserIDNotFound) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/media][%d] getMediaByUserIdNotFound  %+v", 404, o.Payload)
}

func (o *GetMediaByUserIDNotFound) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/media][%d] getMediaByUserIdNotFound  %+v", 404, o.Payload)
}

func (o *GetMediaByUserIDNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetMediaByUserIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMediaByUserIDInternalServerError creates a GetMediaByUserIDInternalServerError with default headers values
func NewGetMediaByUserIDInternalServerError() *GetMediaByUserIDInternalServerError {
	return &GetMediaByUserIDInternalServerError{}
}

/*
GetMediaByUserIDInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetMediaByUserIDInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get media by user Id internal server error response has a 2xx status code
func (o *GetMediaByUserIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get media by user Id internal server error response has a 3xx status code
func (o *GetMediaByUserIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get media by user Id internal server error response has a 4xx status code
func (o *GetMediaByUserIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get media by user Id internal server error response has a 5xx status code
func (o *GetMediaByUserIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get media by user Id internal server error response a status code equal to that given
func (o *GetMediaByUserIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetMediaByUserIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/media][%d] getMediaByUserIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetMediaByUserIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/media][%d] getMediaByUserIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetMediaByUserIDInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetMediaByUserIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
