// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery -name API -inpkg

// API is the interface of the media client
type API interface {
	/*
	   CreateMediaContainer creates an i g container for publishing

	   Create an image, carousel, story or reel IG Container for use in the post publishing process.

	   Limitations:
	   - Containers expire after 24 hours
	   - An Instagram account can only create 400 containers within a rolling 24 hour period
	   - Reels cannot appear in carousels
	   - Stories expire after 24 hours
	*/
	CreateMediaContainer(ctx context.Context, params *CreateMediaContainerParams) (*CreateMediaContainerOK, error)
	/*
	   GetMediaByUserID gets all i g media on an i g user

	   Get all IG Media on an IG User.

	   Limitations:
	   - Returns a maximum of 10K of the most recently created media.
	   - Story IG Media not supported, use the GET /{instagram_account_id}/stories endpoint instead.
	*/
	GetMediaByUserID(ctx context.Context, params *GetMediaByUserIDParams) (*GetMediaByUserIDOK, error)
}

// New creates a new media API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for media API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
CreateMediaContainer creates an i g container for publishing

Create an image, carousel, story or reel IG Container for use in the post publishing process.

Limitations:
- Containers expire after 24 hours
- An Instagram account can only create 400 containers within a rolling 24 hour period
- Reels cannot appear in carousels
- Stories expire after 24 hours
*/
func (a *Client) CreateMediaContainer(ctx context.Context, params *CreateMediaContainerParams) (*CreateMediaContainerOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "CreateMediaContainer",
		Method:             "POST",
		PathPattern:        "/{instagram_account_id}/media",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateMediaContainerReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CreateMediaContainerOK), nil

}

/*
GetMediaByUserID gets all i g media on an i g user

Get all IG Media on an IG User.

Limitations:
- Returns a maximum of 10K of the most recently created media.
- Story IG Media not supported, use the GET /{instagram_account_id}/stories endpoint instead.
*/
func (a *Client) GetMediaByUserID(ctx context.Context, params *GetMediaByUserIDParams) (*GetMediaByUserIDOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetMediaByUserID",
		Method:             "GET",
		PathPattern:        "/{instagram_account_id}/media",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetMediaByUserIDReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetMediaByUserIDOK), nil

}
