// Code generated by go-swagger; DO NOT EDIT.

package stories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qcserestipy/instagram-api-go-client/pkg/sdk/v24.0/account/models"
)

// GetStoriesByUserIDReader is a Reader for the GetStoriesByUserID structure.
type GetStoriesByUserIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStoriesByUserIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStoriesByUserIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetStoriesByUserIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetStoriesByUserIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetStoriesByUserIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetStoriesByUserIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetStoriesByUserIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetStoriesByUserIDOK creates a GetStoriesByUserIDOK with default headers values
func NewGetStoriesByUserIDOK() *GetStoriesByUserIDOK {
	return &GetStoriesByUserIDOK{}
}

/*
GetStoriesByUserIDOK describes a response with status code 200, with default header values.

Return list of story media objects.
*/
type GetStoriesByUserIDOK struct {
	Payload *models.InstagramStories
}

// IsSuccess returns true when this get stories by user Id o k response has a 2xx status code
func (o *GetStoriesByUserIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get stories by user Id o k response has a 3xx status code
func (o *GetStoriesByUserIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get stories by user Id o k response has a 4xx status code
func (o *GetStoriesByUserIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get stories by user Id o k response has a 5xx status code
func (o *GetStoriesByUserIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get stories by user Id o k response a status code equal to that given
func (o *GetStoriesByUserIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetStoriesByUserIDOK) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/stories][%d] getStoriesByUserIdOK  %+v", 200, o.Payload)
}

func (o *GetStoriesByUserIDOK) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/stories][%d] getStoriesByUserIdOK  %+v", 200, o.Payload)
}

func (o *GetStoriesByUserIDOK) GetPayload() *models.InstagramStories {
	return o.Payload
}

func (o *GetStoriesByUserIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InstagramStories)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStoriesByUserIDBadRequest creates a GetStoriesByUserIDBadRequest with default headers values
func NewGetStoriesByUserIDBadRequest() *GetStoriesByUserIDBadRequest {
	return &GetStoriesByUserIDBadRequest{}
}

/*
GetStoriesByUserIDBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetStoriesByUserIDBadRequest struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get stories by user Id bad request response has a 2xx status code
func (o *GetStoriesByUserIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get stories by user Id bad request response has a 3xx status code
func (o *GetStoriesByUserIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get stories by user Id bad request response has a 4xx status code
func (o *GetStoriesByUserIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get stories by user Id bad request response has a 5xx status code
func (o *GetStoriesByUserIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get stories by user Id bad request response a status code equal to that given
func (o *GetStoriesByUserIDBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetStoriesByUserIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/stories][%d] getStoriesByUserIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetStoriesByUserIDBadRequest) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/stories][%d] getStoriesByUserIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetStoriesByUserIDBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetStoriesByUserIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStoriesByUserIDUnauthorized creates a GetStoriesByUserIDUnauthorized with default headers values
func NewGetStoriesByUserIDUnauthorized() *GetStoriesByUserIDUnauthorized {
	return &GetStoriesByUserIDUnauthorized{}
}

/*
GetStoriesByUserIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetStoriesByUserIDUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get stories by user Id unauthorized response has a 2xx status code
func (o *GetStoriesByUserIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get stories by user Id unauthorized response has a 3xx status code
func (o *GetStoriesByUserIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get stories by user Id unauthorized response has a 4xx status code
func (o *GetStoriesByUserIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get stories by user Id unauthorized response has a 5xx status code
func (o *GetStoriesByUserIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get stories by user Id unauthorized response a status code equal to that given
func (o *GetStoriesByUserIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetStoriesByUserIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/stories][%d] getStoriesByUserIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetStoriesByUserIDUnauthorized) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/stories][%d] getStoriesByUserIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetStoriesByUserIDUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetStoriesByUserIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStoriesByUserIDForbidden creates a GetStoriesByUserIDForbidden with default headers values
func NewGetStoriesByUserIDForbidden() *GetStoriesByUserIDForbidden {
	return &GetStoriesByUserIDForbidden{}
}

/*
GetStoriesByUserIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetStoriesByUserIDForbidden struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get stories by user Id forbidden response has a 2xx status code
func (o *GetStoriesByUserIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get stories by user Id forbidden response has a 3xx status code
func (o *GetStoriesByUserIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get stories by user Id forbidden response has a 4xx status code
func (o *GetStoriesByUserIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get stories by user Id forbidden response has a 5xx status code
func (o *GetStoriesByUserIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get stories by user Id forbidden response a status code equal to that given
func (o *GetStoriesByUserIDForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetStoriesByUserIDForbidden) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/stories][%d] getStoriesByUserIdForbidden  %+v", 403, o.Payload)
}

func (o *GetStoriesByUserIDForbidden) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/stories][%d] getStoriesByUserIdForbidden  %+v", 403, o.Payload)
}

func (o *GetStoriesByUserIDForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetStoriesByUserIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStoriesByUserIDNotFound creates a GetStoriesByUserIDNotFound with default headers values
func NewGetStoriesByUserIDNotFound() *GetStoriesByUserIDNotFound {
	return &GetStoriesByUserIDNotFound{}
}

/*
GetStoriesByUserIDNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetStoriesByUserIDNotFound struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get stories by user Id not found response has a 2xx status code
func (o *GetStoriesByUserIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get stories by user Id not found response has a 3xx status code
func (o *GetStoriesByUserIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get stories by user Id not found response has a 4xx status code
func (o *GetStoriesByUserIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get stories by user Id not found response has a 5xx status code
func (o *GetStoriesByUserIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get stories by user Id not found response a status code equal to that given
func (o *GetStoriesByUserIDNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetStoriesByUserIDNotFound) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/stories][%d] getStoriesByUserIdNotFound  %+v", 404, o.Payload)
}

func (o *GetStoriesByUserIDNotFound) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/stories][%d] getStoriesByUserIdNotFound  %+v", 404, o.Payload)
}

func (o *GetStoriesByUserIDNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetStoriesByUserIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStoriesByUserIDInternalServerError creates a GetStoriesByUserIDInternalServerError with default headers values
func NewGetStoriesByUserIDInternalServerError() *GetStoriesByUserIDInternalServerError {
	return &GetStoriesByUserIDInternalServerError{}
}

/*
GetStoriesByUserIDInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetStoriesByUserIDInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get stories by user Id internal server error response has a 2xx status code
func (o *GetStoriesByUserIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get stories by user Id internal server error response has a 3xx status code
func (o *GetStoriesByUserIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get stories by user Id internal server error response has a 4xx status code
func (o *GetStoriesByUserIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get stories by user Id internal server error response has a 5xx status code
func (o *GetStoriesByUserIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get stories by user Id internal server error response a status code equal to that given
func (o *GetStoriesByUserIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetStoriesByUserIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/stories][%d] getStoriesByUserIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetStoriesByUserIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}/stories][%d] getStoriesByUserIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetStoriesByUserIDInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetStoriesByUserIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
