// Code generated by go-swagger; DO NOT EDIT.

package stories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStoriesByUserIDParams creates a new GetStoriesByUserIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetStoriesByUserIDParams() *GetStoriesByUserIDParams {
	return &GetStoriesByUserIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetStoriesByUserIDParamsWithTimeout creates a new GetStoriesByUserIDParams object
// with the ability to set a timeout on a request.
func NewGetStoriesByUserIDParamsWithTimeout(timeout time.Duration) *GetStoriesByUserIDParams {
	return &GetStoriesByUserIDParams{
		timeout: timeout,
	}
}

// NewGetStoriesByUserIDParamsWithContext creates a new GetStoriesByUserIDParams object
// with the ability to set a context for a request.
func NewGetStoriesByUserIDParamsWithContext(ctx context.Context) *GetStoriesByUserIDParams {
	return &GetStoriesByUserIDParams{
		Context: ctx,
	}
}

// NewGetStoriesByUserIDParamsWithHTTPClient creates a new GetStoriesByUserIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetStoriesByUserIDParamsWithHTTPClient(client *http.Client) *GetStoriesByUserIDParams {
	return &GetStoriesByUserIDParams{
		HTTPClient: client,
	}
}

/*
GetStoriesByUserIDParams contains all the parameters to send to the API endpoint

	for the get stories by user ID operation.

	Typically these are written to a http.Request.
*/
type GetStoriesByUserIDParams struct {

	/* XRequestID.

	   An unique ID for the request
	*/
	XRequestID *string

	/* InstagramAccountID.

	   Instagram Account ID (your app user's Instagram professional account ID)
	*/
	InstagramAccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get stories by user ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStoriesByUserIDParams) WithDefaults() *GetStoriesByUserIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get stories by user ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStoriesByUserIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get stories by user ID params
func (o *GetStoriesByUserIDParams) WithTimeout(timeout time.Duration) *GetStoriesByUserIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stories by user ID params
func (o *GetStoriesByUserIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stories by user ID params
func (o *GetStoriesByUserIDParams) WithContext(ctx context.Context) *GetStoriesByUserIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stories by user ID params
func (o *GetStoriesByUserIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stories by user ID params
func (o *GetStoriesByUserIDParams) WithHTTPClient(client *http.Client) *GetStoriesByUserIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stories by user ID params
func (o *GetStoriesByUserIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the get stories by user ID params
func (o *GetStoriesByUserIDParams) WithXRequestID(xRequestID *string) *GetStoriesByUserIDParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the get stories by user ID params
func (o *GetStoriesByUserIDParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithInstagramAccountID adds the instagramAccountID to the get stories by user ID params
func (o *GetStoriesByUserIDParams) WithInstagramAccountID(instagramAccountID string) *GetStoriesByUserIDParams {
	o.SetInstagramAccountID(instagramAccountID)
	return o
}

// SetInstagramAccountID adds the instagramAccountId to the get stories by user ID params
func (o *GetStoriesByUserIDParams) SetInstagramAccountID(instagramAccountID string) {
	o.InstagramAccountID = instagramAccountID
}

// WriteToRequest writes these params to a swagger request
func (o *GetStoriesByUserIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	// path param instagram_account_id
	if err := r.SetPathParam("instagram_account_id", o.InstagramAccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
