// Code generated by go-swagger; DO NOT EDIT.

package stories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery -name API -inpkg

// API is the interface of the stories client
type API interface {
	/*
	   GetStoriesByUserID gets stories for an instagram user

	   Returns a list of story IG Media objects on an IG User.

	   Limitations:
	   - Responses will not include Live Video stories.
	   - Stories are only available for 24 hours.
	   - New stories created when a user reshares a story will not be returned.
	   - Only one caption will be returned per Instagram story, even if more than one caption exists.
	*/
	GetStoriesByUserID(ctx context.Context, params *GetStoriesByUserIDParams) (*GetStoriesByUserIDOK, error)
}

// New creates a new stories API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for stories API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
GetStoriesByUserID gets stories for an instagram user

Returns a list of story IG Media objects on an IG User.

Limitations:
- Responses will not include Live Video stories.
- Stories are only available for 24 hours.
- New stories created when a user reshares a story will not be returned.
- Only one caption will be returned per Instagram story, even if more than one caption exists.
*/
func (a *Client) GetStoriesByUserID(ctx context.Context, params *GetStoriesByUserIDParams) (*GetStoriesByUserIDOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetStoriesByUserID",
		Method:             "GET",
		PathPattern:        "/{instagram_account_id}/stories",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetStoriesByUserIDReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetStoriesByUserIDOK), nil

}
