// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"net/url"

	"github.com/go-openapi/runtime"
	rtclient "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/qcserestipy/instagram-api-go-client/pkg/sdk/v24.0/account/client/insights"
	"github.com/qcserestipy/instagram-api-go-client/pkg/sdk/v24.0/account/client/media"
	"github.com/qcserestipy/instagram-api-go-client/pkg/sdk/v24.0/account/client/stories"
)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "graph.facebook.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/v24.0"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

type Config struct {
	// URL is the base URL of the upstream server
	URL *url.URL
	// Transport is an inner transport for the client
	Transport http.RoundTripper
	// AuthInfo is for authentication
	AuthInfo runtime.ClientAuthInfoWriter
}

// New creates a new instagram account insights API HTTP client.
func New(c Config) *InstagramAccountInsightsAPI {
	var (
		host     = DefaultHost
		basePath = DefaultBasePath
		schemes  = DefaultSchemes
	)

	if c.URL != nil {
		host = c.URL.Host
		basePath = c.URL.Path
		schemes = []string{c.URL.Scheme}
	}

	transport := rtclient.New(host, basePath, schemes)
	if c.Transport != nil {
		transport.Transport = c.Transport
	}

	cli := new(InstagramAccountInsightsAPI)
	cli.Transport = transport
	cli.Insights = insights.New(transport, strfmt.Default, c.AuthInfo)
	cli.Media = media.New(transport, strfmt.Default, c.AuthInfo)
	cli.Stories = stories.New(transport, strfmt.Default, c.AuthInfo)
	return cli
}

// InstagramAccountInsightsAPI is a client for instagram account insights API
type InstagramAccountInsightsAPI struct {
	Insights  *insights.Client
	Media     *media.Client
	Stories   *stories.Client
	Transport runtime.ClientTransport
}
