// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InstagramUser Instagram Business or Creator Account object. Fields returned depend on the `fields` query parameter.
//
// swagger:model InstagramUser
type InstagramUser struct {

	// Public biography text
	Biography string `json:"biography,omitempty"`

	// Number of followers
	FollowersCount int64 `json:"followers_count,omitempty"`

	// Number of accounts this user follows
	FollowsCount int64 `json:"follows_count,omitempty"`

	// Whether the account has a profile picture
	HasProfilePic bool `json:"has_profile_pic,omitempty"`

	// Instagram User ID
	ID string `json:"id,omitempty"`

	// Whether the account is published
	IsPublished bool `json:"is_published,omitempty"`

	// Legacy user id, if available
	LegacyInstagramUserID string `json:"legacy_instagram_user_id,omitempty"`

	// Number of media objects
	MediaCount int64 `json:"media_count,omitempty"`

	// Display name
	Name string `json:"name,omitempty"`

	// URL to profile picture
	ProfilePictureURL string `json:"profile_picture_url,omitempty"`

	// Shopping product tag eligibility for the account
	ShoppingProductTagEligibility string `json:"shopping_product_tag_eligibility,omitempty"`

	// Instagram username
	Username string `json:"username,omitempty"`

	// Website URL set on profile
	Website string `json:"website,omitempty"`
}

// Validate validates this instagram user
func (m *InstagramUser) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this instagram user based on context it is used
func (m *InstagramUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InstagramUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InstagramUser) UnmarshalBinary(b []byte) error {
	var res InstagramUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
