// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MediaContainerCreated media container created
//
// swagger:model MediaContainerCreated
type MediaContainerCreated struct {

	// Instagram Container ID
	ID string `json:"id,omitempty"`

	// URI for resumable upload (only returned for resumable upload type)
	URI string `json:"uri,omitempty"`
}

// Validate validates this media container created
func (m *MediaContainerCreated) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this media container created based on context it is used
func (m *MediaContainerCreated) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MediaContainerCreated) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MediaContainerCreated) UnmarshalBinary(b []byte) error {
	var res MediaContainerCreated
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
