// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MediaItem media item
//
// swagger:model MediaItem
type MediaItem struct {

	// Instagram Media ID
	ID string `json:"id,omitempty"`
}

// Validate validates this media item
func (m *MediaItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this media item based on context it is used
func (m *MediaItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MediaItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MediaItem) UnmarshalBinary(b []byte) error {
	var res MediaItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
