// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StoryMediaItem story media item
//
// swagger:model StoryMediaItem
type StoryMediaItem struct {

	// Instagram Media ID for the story
	ID string `json:"id,omitempty"`
}

// Validate validates this story media item
func (m *StoryMediaItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this story media item based on context it is used
func (m *StoryMediaItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StoryMediaItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StoryMediaItem) UnmarshalBinary(b []byte) error {
	var res StoryMediaItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
