// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qcserestipy/instagram-api-go-client/pkg/sdk/v24.0/media/models"
)

// GetMediaByIDReader is a Reader for the GetMediaByID structure.
type GetMediaByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMediaByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMediaByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetMediaByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetMediaByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetMediaByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetMediaByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetMediaByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetMediaByIDOK creates a GetMediaByIDOK with default headers values
func NewGetMediaByIDOK() *GetMediaByIDOK {
	return &GetMediaByIDOK{}
}

/*
GetMediaByIDOK describes a response with status code 200, with default header values.

Return Instagram media object with requested fields.
*/
type GetMediaByIDOK struct {
	Payload *models.InstagramMediaObject
}

// IsSuccess returns true when this get media by Id o k response has a 2xx status code
func (o *GetMediaByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get media by Id o k response has a 3xx status code
func (o *GetMediaByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get media by Id o k response has a 4xx status code
func (o *GetMediaByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get media by Id o k response has a 5xx status code
func (o *GetMediaByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get media by Id o k response a status code equal to that given
func (o *GetMediaByIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetMediaByIDOK) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}][%d] getMediaByIdOK  %+v", 200, o.Payload)
}

func (o *GetMediaByIDOK) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}][%d] getMediaByIdOK  %+v", 200, o.Payload)
}

func (o *GetMediaByIDOK) GetPayload() *models.InstagramMediaObject {
	return o.Payload
}

func (o *GetMediaByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InstagramMediaObject)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMediaByIDBadRequest creates a GetMediaByIDBadRequest with default headers values
func NewGetMediaByIDBadRequest() *GetMediaByIDBadRequest {
	return &GetMediaByIDBadRequest{}
}

/*
GetMediaByIDBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetMediaByIDBadRequest struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get media by Id bad request response has a 2xx status code
func (o *GetMediaByIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get media by Id bad request response has a 3xx status code
func (o *GetMediaByIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get media by Id bad request response has a 4xx status code
func (o *GetMediaByIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get media by Id bad request response has a 5xx status code
func (o *GetMediaByIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get media by Id bad request response a status code equal to that given
func (o *GetMediaByIDBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetMediaByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}][%d] getMediaByIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetMediaByIDBadRequest) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}][%d] getMediaByIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetMediaByIDBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetMediaByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMediaByIDUnauthorized creates a GetMediaByIDUnauthorized with default headers values
func NewGetMediaByIDUnauthorized() *GetMediaByIDUnauthorized {
	return &GetMediaByIDUnauthorized{}
}

/*
GetMediaByIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetMediaByIDUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get media by Id unauthorized response has a 2xx status code
func (o *GetMediaByIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get media by Id unauthorized response has a 3xx status code
func (o *GetMediaByIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get media by Id unauthorized response has a 4xx status code
func (o *GetMediaByIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get media by Id unauthorized response has a 5xx status code
func (o *GetMediaByIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get media by Id unauthorized response a status code equal to that given
func (o *GetMediaByIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetMediaByIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}][%d] getMediaByIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetMediaByIDUnauthorized) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}][%d] getMediaByIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetMediaByIDUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetMediaByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMediaByIDForbidden creates a GetMediaByIDForbidden with default headers values
func NewGetMediaByIDForbidden() *GetMediaByIDForbidden {
	return &GetMediaByIDForbidden{}
}

/*
GetMediaByIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetMediaByIDForbidden struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get media by Id forbidden response has a 2xx status code
func (o *GetMediaByIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get media by Id forbidden response has a 3xx status code
func (o *GetMediaByIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get media by Id forbidden response has a 4xx status code
func (o *GetMediaByIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get media by Id forbidden response has a 5xx status code
func (o *GetMediaByIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get media by Id forbidden response a status code equal to that given
func (o *GetMediaByIDForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetMediaByIDForbidden) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}][%d] getMediaByIdForbidden  %+v", 403, o.Payload)
}

func (o *GetMediaByIDForbidden) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}][%d] getMediaByIdForbidden  %+v", 403, o.Payload)
}

func (o *GetMediaByIDForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetMediaByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMediaByIDNotFound creates a GetMediaByIDNotFound with default headers values
func NewGetMediaByIDNotFound() *GetMediaByIDNotFound {
	return &GetMediaByIDNotFound{}
}

/*
GetMediaByIDNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetMediaByIDNotFound struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get media by Id not found response has a 2xx status code
func (o *GetMediaByIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get media by Id not found response has a 3xx status code
func (o *GetMediaByIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get media by Id not found response has a 4xx status code
func (o *GetMediaByIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get media by Id not found response has a 5xx status code
func (o *GetMediaByIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get media by Id not found response a status code equal to that given
func (o *GetMediaByIDNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetMediaByIDNotFound) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}][%d] getMediaByIdNotFound  %+v", 404, o.Payload)
}

func (o *GetMediaByIDNotFound) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}][%d] getMediaByIdNotFound  %+v", 404, o.Payload)
}

func (o *GetMediaByIDNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetMediaByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMediaByIDInternalServerError creates a GetMediaByIDInternalServerError with default headers values
func NewGetMediaByIDInternalServerError() *GetMediaByIDInternalServerError {
	return &GetMediaByIDInternalServerError{}
}

/*
GetMediaByIDInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetMediaByIDInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get media by Id internal server error response has a 2xx status code
func (o *GetMediaByIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get media by Id internal server error response has a 3xx status code
func (o *GetMediaByIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get media by Id internal server error response has a 4xx status code
func (o *GetMediaByIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get media by Id internal server error response has a 5xx status code
func (o *GetMediaByIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get media by Id internal server error response a status code equal to that given
func (o *GetMediaByIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetMediaByIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}][%d] getMediaByIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetMediaByIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}][%d] getMediaByIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetMediaByIDInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetMediaByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
