// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMediaByIDParams creates a new GetMediaByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMediaByIDParams() *GetMediaByIDParams {
	return &GetMediaByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMediaByIDParamsWithTimeout creates a new GetMediaByIDParams object
// with the ability to set a timeout on a request.
func NewGetMediaByIDParamsWithTimeout(timeout time.Duration) *GetMediaByIDParams {
	return &GetMediaByIDParams{
		timeout: timeout,
	}
}

// NewGetMediaByIDParamsWithContext creates a new GetMediaByIDParams object
// with the ability to set a context for a request.
func NewGetMediaByIDParamsWithContext(ctx context.Context) *GetMediaByIDParams {
	return &GetMediaByIDParams{
		Context: ctx,
	}
}

// NewGetMediaByIDParamsWithHTTPClient creates a new GetMediaByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMediaByIDParamsWithHTTPClient(client *http.Client) *GetMediaByIDParams {
	return &GetMediaByIDParams{
		HTTPClient: client,
	}
}

/*
GetMediaByIDParams contains all the parameters to send to the API endpoint

	for the get media by ID operation.

	Typically these are written to a http.Request.
*/
type GetMediaByIDParams struct {

	/* XRequestID.

	   An unique ID for the request
	*/
	XRequestID *string

	/* Fields.

	   Comma-separated list of fields you want returned (e.g., id,media_type,media_url,caption,timestamp,username,like_count,comments_count)
	*/
	Fields *string

	/* InstagramMediaID.

	   Instagram Media ID
	*/
	InstagramMediaID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get media by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMediaByIDParams) WithDefaults() *GetMediaByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get media by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMediaByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get media by ID params
func (o *GetMediaByIDParams) WithTimeout(timeout time.Duration) *GetMediaByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get media by ID params
func (o *GetMediaByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get media by ID params
func (o *GetMediaByIDParams) WithContext(ctx context.Context) *GetMediaByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get media by ID params
func (o *GetMediaByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get media by ID params
func (o *GetMediaByIDParams) WithHTTPClient(client *http.Client) *GetMediaByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get media by ID params
func (o *GetMediaByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the get media by ID params
func (o *GetMediaByIDParams) WithXRequestID(xRequestID *string) *GetMediaByIDParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the get media by ID params
func (o *GetMediaByIDParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithFields adds the fields to the get media by ID params
func (o *GetMediaByIDParams) WithFields(fields *string) *GetMediaByIDParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get media by ID params
func (o *GetMediaByIDParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithInstagramMediaID adds the instagramMediaID to the get media by ID params
func (o *GetMediaByIDParams) WithInstagramMediaID(instagramMediaID string) *GetMediaByIDParams {
	o.SetInstagramMediaID(instagramMediaID)
	return o
}

// SetInstagramMediaID adds the instagramMediaId to the get media by ID params
func (o *GetMediaByIDParams) SetInstagramMediaID(instagramMediaID string) {
	o.InstagramMediaID = instagramMediaID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMediaByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	// path param instagram_media_id
	if err := r.SetPathParam("instagram_media_id", o.InstagramMediaID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
