// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery -name API -inpkg

// API is the interface of the media client
type API interface {
	/*
	   GetMediaByID gets fields and edges on instagram media

	   Gets fields and edges on Instagram media (album, photo, video, reel, or story).

	   Limitations:
	   - Fields that return aggregated values don't include ads-driven data.
	   - Captions don't include the @ symbol unless the app user can perform admin-equivalent tasks.
	   - Some fields, such as permalink, cannot be used on photos within albums (children).
	   - Live video Instagram Media can only be read while they are being broadcast.
	   - This API returns only data for media owned by Instagram professional accounts, not personal accounts.
	*/
	GetMediaByID(ctx context.Context, params *GetMediaByIDParams) (*GetMediaByIDOK, error)
	/*
	   UpdateMediaComments enables or disable comments on an instagram media

	   Enable or disable comments on an Instagram Media.

	   Limitations:
	   - Live video Instagram Media not supported.
	*/
	UpdateMediaComments(ctx context.Context, params *UpdateMediaCommentsParams) (*UpdateMediaCommentsOK, error)
}

// New creates a new media API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for media API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
GetMediaByID gets fields and edges on instagram media

Gets fields and edges on Instagram media (album, photo, video, reel, or story).

Limitations:
- Fields that return aggregated values don't include ads-driven data.
- Captions don't include the @ symbol unless the app user can perform admin-equivalent tasks.
- Some fields, such as permalink, cannot be used on photos within albums (children).
- Live video Instagram Media can only be read while they are being broadcast.
- This API returns only data for media owned by Instagram professional accounts, not personal accounts.
*/
func (a *Client) GetMediaByID(ctx context.Context, params *GetMediaByIDParams) (*GetMediaByIDOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetMediaByID",
		Method:             "GET",
		PathPattern:        "/{instagram_media_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetMediaByIDReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetMediaByIDOK), nil

}

/*
UpdateMediaComments enables or disable comments on an instagram media

Enable or disable comments on an Instagram Media.

Limitations:
- Live video Instagram Media not supported.
*/
func (a *Client) UpdateMediaComments(ctx context.Context, params *UpdateMediaCommentsParams) (*UpdateMediaCommentsOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "UpdateMediaComments",
		Method:             "POST",
		PathPattern:        "/{instagram_media_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateMediaCommentsReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*UpdateMediaCommentsOK), nil

}
