// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUpdateMediaCommentsParams creates a new UpdateMediaCommentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateMediaCommentsParams() *UpdateMediaCommentsParams {
	return &UpdateMediaCommentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateMediaCommentsParamsWithTimeout creates a new UpdateMediaCommentsParams object
// with the ability to set a timeout on a request.
func NewUpdateMediaCommentsParamsWithTimeout(timeout time.Duration) *UpdateMediaCommentsParams {
	return &UpdateMediaCommentsParams{
		timeout: timeout,
	}
}

// NewUpdateMediaCommentsParamsWithContext creates a new UpdateMediaCommentsParams object
// with the ability to set a context for a request.
func NewUpdateMediaCommentsParamsWithContext(ctx context.Context) *UpdateMediaCommentsParams {
	return &UpdateMediaCommentsParams{
		Context: ctx,
	}
}

// NewUpdateMediaCommentsParamsWithHTTPClient creates a new UpdateMediaCommentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateMediaCommentsParamsWithHTTPClient(client *http.Client) *UpdateMediaCommentsParams {
	return &UpdateMediaCommentsParams{
		HTTPClient: client,
	}
}

/*
UpdateMediaCommentsParams contains all the parameters to send to the API endpoint

	for the update media comments operation.

	Typically these are written to a http.Request.
*/
type UpdateMediaCommentsParams struct {

	/* XRequestID.

	   An unique ID for the request
	*/
	XRequestID *string

	/* CommentEnabled.

	   Required. Set to true to enable comments or false to disable comments.
	*/
	CommentEnabled bool

	/* InstagramMediaID.

	   Instagram Media ID
	*/
	InstagramMediaID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update media comments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateMediaCommentsParams) WithDefaults() *UpdateMediaCommentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update media comments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateMediaCommentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update media comments params
func (o *UpdateMediaCommentsParams) WithTimeout(timeout time.Duration) *UpdateMediaCommentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update media comments params
func (o *UpdateMediaCommentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update media comments params
func (o *UpdateMediaCommentsParams) WithContext(ctx context.Context) *UpdateMediaCommentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update media comments params
func (o *UpdateMediaCommentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update media comments params
func (o *UpdateMediaCommentsParams) WithHTTPClient(client *http.Client) *UpdateMediaCommentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update media comments params
func (o *UpdateMediaCommentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the update media comments params
func (o *UpdateMediaCommentsParams) WithXRequestID(xRequestID *string) *UpdateMediaCommentsParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the update media comments params
func (o *UpdateMediaCommentsParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithCommentEnabled adds the commentEnabled to the update media comments params
func (o *UpdateMediaCommentsParams) WithCommentEnabled(commentEnabled bool) *UpdateMediaCommentsParams {
	o.SetCommentEnabled(commentEnabled)
	return o
}

// SetCommentEnabled adds the commentEnabled to the update media comments params
func (o *UpdateMediaCommentsParams) SetCommentEnabled(commentEnabled bool) {
	o.CommentEnabled = commentEnabled
}

// WithInstagramMediaID adds the instagramMediaID to the update media comments params
func (o *UpdateMediaCommentsParams) WithInstagramMediaID(instagramMediaID string) *UpdateMediaCommentsParams {
	o.SetInstagramMediaID(instagramMediaID)
	return o
}

// SetInstagramMediaID adds the instagramMediaId to the update media comments params
func (o *UpdateMediaCommentsParams) SetInstagramMediaID(instagramMediaID string) {
	o.InstagramMediaID = instagramMediaID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateMediaCommentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	// query param comment_enabled
	qrCommentEnabled := o.CommentEnabled
	qCommentEnabled := swag.FormatBool(qrCommentEnabled)
	if qCommentEnabled != "" {

		if err := r.SetQueryParam("comment_enabled", qCommentEnabled); err != nil {
			return err
		}
	}

	// path param instagram_media_id
	if err := r.SetPathParam("instagram_media_id", o.InstagramMediaID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
