// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qcserestipy/instagram-api-go-client/pkg/sdk/v24.0/media/models"
)

// UpdateMediaCommentsReader is a Reader for the UpdateMediaComments structure.
type UpdateMediaCommentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateMediaCommentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateMediaCommentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateMediaCommentsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateMediaCommentsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateMediaCommentsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateMediaCommentsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateMediaCommentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateMediaCommentsOK creates a UpdateMediaCommentsOK with default headers values
func NewUpdateMediaCommentsOK() *UpdateMediaCommentsOK {
	return &UpdateMediaCommentsOK{}
}

/*
UpdateMediaCommentsOK describes a response with status code 200, with default header values.

Comments enabled/disabled successfully.
*/
type UpdateMediaCommentsOK struct {
	Payload *models.Success
}

// IsSuccess returns true when this update media comments o k response has a 2xx status code
func (o *UpdateMediaCommentsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update media comments o k response has a 3xx status code
func (o *UpdateMediaCommentsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update media comments o k response has a 4xx status code
func (o *UpdateMediaCommentsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update media comments o k response has a 5xx status code
func (o *UpdateMediaCommentsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update media comments o k response a status code equal to that given
func (o *UpdateMediaCommentsOK) IsCode(code int) bool {
	return code == 200
}

func (o *UpdateMediaCommentsOK) Error() string {
	return fmt.Sprintf("[POST /{instagram_media_id}][%d] updateMediaCommentsOK  %+v", 200, o.Payload)
}

func (o *UpdateMediaCommentsOK) String() string {
	return fmt.Sprintf("[POST /{instagram_media_id}][%d] updateMediaCommentsOK  %+v", 200, o.Payload)
}

func (o *UpdateMediaCommentsOK) GetPayload() *models.Success {
	return o.Payload
}

func (o *UpdateMediaCommentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Success)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateMediaCommentsBadRequest creates a UpdateMediaCommentsBadRequest with default headers values
func NewUpdateMediaCommentsBadRequest() *UpdateMediaCommentsBadRequest {
	return &UpdateMediaCommentsBadRequest{}
}

/*
UpdateMediaCommentsBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type UpdateMediaCommentsBadRequest struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this update media comments bad request response has a 2xx status code
func (o *UpdateMediaCommentsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update media comments bad request response has a 3xx status code
func (o *UpdateMediaCommentsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update media comments bad request response has a 4xx status code
func (o *UpdateMediaCommentsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update media comments bad request response has a 5xx status code
func (o *UpdateMediaCommentsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update media comments bad request response a status code equal to that given
func (o *UpdateMediaCommentsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *UpdateMediaCommentsBadRequest) Error() string {
	return fmt.Sprintf("[POST /{instagram_media_id}][%d] updateMediaCommentsBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateMediaCommentsBadRequest) String() string {
	return fmt.Sprintf("[POST /{instagram_media_id}][%d] updateMediaCommentsBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateMediaCommentsBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *UpdateMediaCommentsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateMediaCommentsUnauthorized creates a UpdateMediaCommentsUnauthorized with default headers values
func NewUpdateMediaCommentsUnauthorized() *UpdateMediaCommentsUnauthorized {
	return &UpdateMediaCommentsUnauthorized{}
}

/*
UpdateMediaCommentsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type UpdateMediaCommentsUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this update media comments unauthorized response has a 2xx status code
func (o *UpdateMediaCommentsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update media comments unauthorized response has a 3xx status code
func (o *UpdateMediaCommentsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update media comments unauthorized response has a 4xx status code
func (o *UpdateMediaCommentsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this update media comments unauthorized response has a 5xx status code
func (o *UpdateMediaCommentsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this update media comments unauthorized response a status code equal to that given
func (o *UpdateMediaCommentsUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *UpdateMediaCommentsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /{instagram_media_id}][%d] updateMediaCommentsUnauthorized  %+v", 401, o.Payload)
}

func (o *UpdateMediaCommentsUnauthorized) String() string {
	return fmt.Sprintf("[POST /{instagram_media_id}][%d] updateMediaCommentsUnauthorized  %+v", 401, o.Payload)
}

func (o *UpdateMediaCommentsUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *UpdateMediaCommentsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateMediaCommentsForbidden creates a UpdateMediaCommentsForbidden with default headers values
func NewUpdateMediaCommentsForbidden() *UpdateMediaCommentsForbidden {
	return &UpdateMediaCommentsForbidden{}
}

/*
UpdateMediaCommentsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type UpdateMediaCommentsForbidden struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this update media comments forbidden response has a 2xx status code
func (o *UpdateMediaCommentsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update media comments forbidden response has a 3xx status code
func (o *UpdateMediaCommentsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update media comments forbidden response has a 4xx status code
func (o *UpdateMediaCommentsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this update media comments forbidden response has a 5xx status code
func (o *UpdateMediaCommentsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this update media comments forbidden response a status code equal to that given
func (o *UpdateMediaCommentsForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *UpdateMediaCommentsForbidden) Error() string {
	return fmt.Sprintf("[POST /{instagram_media_id}][%d] updateMediaCommentsForbidden  %+v", 403, o.Payload)
}

func (o *UpdateMediaCommentsForbidden) String() string {
	return fmt.Sprintf("[POST /{instagram_media_id}][%d] updateMediaCommentsForbidden  %+v", 403, o.Payload)
}

func (o *UpdateMediaCommentsForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *UpdateMediaCommentsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateMediaCommentsNotFound creates a UpdateMediaCommentsNotFound with default headers values
func NewUpdateMediaCommentsNotFound() *UpdateMediaCommentsNotFound {
	return &UpdateMediaCommentsNotFound{}
}

/*
UpdateMediaCommentsNotFound describes a response with status code 404, with default header values.

Not found
*/
type UpdateMediaCommentsNotFound struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this update media comments not found response has a 2xx status code
func (o *UpdateMediaCommentsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update media comments not found response has a 3xx status code
func (o *UpdateMediaCommentsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update media comments not found response has a 4xx status code
func (o *UpdateMediaCommentsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update media comments not found response has a 5xx status code
func (o *UpdateMediaCommentsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update media comments not found response a status code equal to that given
func (o *UpdateMediaCommentsNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *UpdateMediaCommentsNotFound) Error() string {
	return fmt.Sprintf("[POST /{instagram_media_id}][%d] updateMediaCommentsNotFound  %+v", 404, o.Payload)
}

func (o *UpdateMediaCommentsNotFound) String() string {
	return fmt.Sprintf("[POST /{instagram_media_id}][%d] updateMediaCommentsNotFound  %+v", 404, o.Payload)
}

func (o *UpdateMediaCommentsNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *UpdateMediaCommentsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateMediaCommentsInternalServerError creates a UpdateMediaCommentsInternalServerError with default headers values
func NewUpdateMediaCommentsInternalServerError() *UpdateMediaCommentsInternalServerError {
	return &UpdateMediaCommentsInternalServerError{}
}

/*
UpdateMediaCommentsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type UpdateMediaCommentsInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this update media comments internal server error response has a 2xx status code
func (o *UpdateMediaCommentsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update media comments internal server error response has a 3xx status code
func (o *UpdateMediaCommentsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update media comments internal server error response has a 4xx status code
func (o *UpdateMediaCommentsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this update media comments internal server error response has a 5xx status code
func (o *UpdateMediaCommentsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this update media comments internal server error response a status code equal to that given
func (o *UpdateMediaCommentsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *UpdateMediaCommentsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /{instagram_media_id}][%d] updateMediaCommentsInternalServerError  %+v", 500, o.Payload)
}

func (o *UpdateMediaCommentsInternalServerError) String() string {
	return fmt.Sprintf("[POST /{instagram_media_id}][%d] updateMediaCommentsInternalServerError  %+v", 500, o.Payload)
}

func (o *UpdateMediaCommentsInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *UpdateMediaCommentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
