// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery -name API -inpkg

// API is the interface of the comments client
type API interface {
	/*
	   CreateCommentOnMedia creates a comment on an instagram media object

	   Creates an IG Comment on an IG Media object.

	   Limitations:
	   - Comments on live video IG Media are not supported.
	*/
	CreateCommentOnMedia(ctx context.Context, params *CreateCommentOnMediaParams) (*CreateCommentOnMediaOK, error)
	/*
	   GetCommentsByMediaID gets comments on an instagram media object

	   Returns a list of IG Comments on an IG Media object.

	   Limitations:
	   - Requests made using API version 3.1 or older will have results returned in chronological order. Requests made using version 3.2+ will have results returned in reverse chronological order.
	   - Returns only top-level comments. Replies to comments are not included unless you use field expansion to request the replies field.
	   - Returns a maximum of 50 comments per query.
	   - Comments cannot be filtered by timestamp.
	   - Comments on live video IG Media are not supported.

	   Note: Non-organic comments (comments on Ads containing IG Media) are not supported. Use the Marketing API to get non-organic comments.
	*/
	GetCommentsByMediaID(ctx context.Context, params *GetCommentsByMediaIDParams) (*GetCommentsByMediaIDOK, error)
}

// New creates a new comments API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for comments API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
CreateCommentOnMedia creates a comment on an instagram media object

Creates an IG Comment on an IG Media object.

Limitations:
- Comments on live video IG Media are not supported.
*/
func (a *Client) CreateCommentOnMedia(ctx context.Context, params *CreateCommentOnMediaParams) (*CreateCommentOnMediaOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "CreateCommentOnMedia",
		Method:             "POST",
		PathPattern:        "/{instagram_media_id}/comments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateCommentOnMediaReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CreateCommentOnMediaOK), nil

}

/*
GetCommentsByMediaID gets comments on an instagram media object

Returns a list of IG Comments on an IG Media object.

Limitations:
- Requests made using API version 3.1 or older will have results returned in chronological order. Requests made using version 3.2+ will have results returned in reverse chronological order.
- Returns only top-level comments. Replies to comments are not included unless you use field expansion to request the replies field.
- Returns a maximum of 50 comments per query.
- Comments cannot be filtered by timestamp.
- Comments on live video IG Media are not supported.

Note: Non-organic comments (comments on Ads containing IG Media) are not supported. Use the Marketing API to get non-organic comments.
*/
func (a *Client) GetCommentsByMediaID(ctx context.Context, params *GetCommentsByMediaIDParams) (*GetCommentsByMediaIDOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetCommentsByMediaID",
		Method:             "GET",
		PathPattern:        "/{instagram_media_id}/comments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetCommentsByMediaIDReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetCommentsByMediaIDOK), nil

}
