// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateCommentOnMediaParams creates a new CreateCommentOnMediaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateCommentOnMediaParams() *CreateCommentOnMediaParams {
	return &CreateCommentOnMediaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCommentOnMediaParamsWithTimeout creates a new CreateCommentOnMediaParams object
// with the ability to set a timeout on a request.
func NewCreateCommentOnMediaParamsWithTimeout(timeout time.Duration) *CreateCommentOnMediaParams {
	return &CreateCommentOnMediaParams{
		timeout: timeout,
	}
}

// NewCreateCommentOnMediaParamsWithContext creates a new CreateCommentOnMediaParams object
// with the ability to set a context for a request.
func NewCreateCommentOnMediaParamsWithContext(ctx context.Context) *CreateCommentOnMediaParams {
	return &CreateCommentOnMediaParams{
		Context: ctx,
	}
}

// NewCreateCommentOnMediaParamsWithHTTPClient creates a new CreateCommentOnMediaParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateCommentOnMediaParamsWithHTTPClient(client *http.Client) *CreateCommentOnMediaParams {
	return &CreateCommentOnMediaParams{
		HTTPClient: client,
	}
}

/*
CreateCommentOnMediaParams contains all the parameters to send to the API endpoint

	for the create comment on media operation.

	Typically these are written to a http.Request.
*/
type CreateCommentOnMediaParams struct {

	/* XRequestID.

	   An unique ID for the request
	*/
	XRequestID *string

	/* InstagramMediaID.

	   Instagram Media ID
	*/
	InstagramMediaID string

	/* Message.

	   Required. The text to be included in the comment.
	*/
	Message string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create comment on media params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateCommentOnMediaParams) WithDefaults() *CreateCommentOnMediaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create comment on media params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateCommentOnMediaParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create comment on media params
func (o *CreateCommentOnMediaParams) WithTimeout(timeout time.Duration) *CreateCommentOnMediaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create comment on media params
func (o *CreateCommentOnMediaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create comment on media params
func (o *CreateCommentOnMediaParams) WithContext(ctx context.Context) *CreateCommentOnMediaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create comment on media params
func (o *CreateCommentOnMediaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create comment on media params
func (o *CreateCommentOnMediaParams) WithHTTPClient(client *http.Client) *CreateCommentOnMediaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create comment on media params
func (o *CreateCommentOnMediaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the create comment on media params
func (o *CreateCommentOnMediaParams) WithXRequestID(xRequestID *string) *CreateCommentOnMediaParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the create comment on media params
func (o *CreateCommentOnMediaParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithInstagramMediaID adds the instagramMediaID to the create comment on media params
func (o *CreateCommentOnMediaParams) WithInstagramMediaID(instagramMediaID string) *CreateCommentOnMediaParams {
	o.SetInstagramMediaID(instagramMediaID)
	return o
}

// SetInstagramMediaID adds the instagramMediaId to the create comment on media params
func (o *CreateCommentOnMediaParams) SetInstagramMediaID(instagramMediaID string) {
	o.InstagramMediaID = instagramMediaID
}

// WithMessage adds the message to the create comment on media params
func (o *CreateCommentOnMediaParams) WithMessage(message string) *CreateCommentOnMediaParams {
	o.SetMessage(message)
	return o
}

// SetMessage adds the message to the create comment on media params
func (o *CreateCommentOnMediaParams) SetMessage(message string) {
	o.Message = message
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCommentOnMediaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	// path param instagram_media_id
	if err := r.SetPathParam("instagram_media_id", o.InstagramMediaID); err != nil {
		return err
	}

	// query param message
	qrMessage := o.Message
	qMessage := qrMessage
	if qMessage != "" {

		if err := r.SetQueryParam("message", qMessage); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
