// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qcserestipy/instagram-api-go-client/pkg/sdk/v24.0/media/models"
)

// CreateCommentOnMediaReader is a Reader for the CreateCommentOnMedia structure.
type CreateCommentOnMediaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCommentOnMediaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateCommentOnMediaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateCommentOnMediaBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateCommentOnMediaUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateCommentOnMediaForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateCommentOnMediaNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateCommentOnMediaInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateCommentOnMediaOK creates a CreateCommentOnMediaOK with default headers values
func NewCreateCommentOnMediaOK() *CreateCommentOnMediaOK {
	return &CreateCommentOnMediaOK{}
}

/*
CreateCommentOnMediaOK describes a response with status code 200, with default header values.

Comment created successfully.
*/
type CreateCommentOnMediaOK struct {
	Payload *models.CommentCreated
}

// IsSuccess returns true when this create comment on media o k response has a 2xx status code
func (o *CreateCommentOnMediaOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create comment on media o k response has a 3xx status code
func (o *CreateCommentOnMediaOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create comment on media o k response has a 4xx status code
func (o *CreateCommentOnMediaOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create comment on media o k response has a 5xx status code
func (o *CreateCommentOnMediaOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create comment on media o k response a status code equal to that given
func (o *CreateCommentOnMediaOK) IsCode(code int) bool {
	return code == 200
}

func (o *CreateCommentOnMediaOK) Error() string {
	return fmt.Sprintf("[POST /{instagram_media_id}/comments][%d] createCommentOnMediaOK  %+v", 200, o.Payload)
}

func (o *CreateCommentOnMediaOK) String() string {
	return fmt.Sprintf("[POST /{instagram_media_id}/comments][%d] createCommentOnMediaOK  %+v", 200, o.Payload)
}

func (o *CreateCommentOnMediaOK) GetPayload() *models.CommentCreated {
	return o.Payload
}

func (o *CreateCommentOnMediaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommentCreated)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCommentOnMediaBadRequest creates a CreateCommentOnMediaBadRequest with default headers values
func NewCreateCommentOnMediaBadRequest() *CreateCommentOnMediaBadRequest {
	return &CreateCommentOnMediaBadRequest{}
}

/*
CreateCommentOnMediaBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type CreateCommentOnMediaBadRequest struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this create comment on media bad request response has a 2xx status code
func (o *CreateCommentOnMediaBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create comment on media bad request response has a 3xx status code
func (o *CreateCommentOnMediaBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create comment on media bad request response has a 4xx status code
func (o *CreateCommentOnMediaBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create comment on media bad request response has a 5xx status code
func (o *CreateCommentOnMediaBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create comment on media bad request response a status code equal to that given
func (o *CreateCommentOnMediaBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CreateCommentOnMediaBadRequest) Error() string {
	return fmt.Sprintf("[POST /{instagram_media_id}/comments][%d] createCommentOnMediaBadRequest  %+v", 400, o.Payload)
}

func (o *CreateCommentOnMediaBadRequest) String() string {
	return fmt.Sprintf("[POST /{instagram_media_id}/comments][%d] createCommentOnMediaBadRequest  %+v", 400, o.Payload)
}

func (o *CreateCommentOnMediaBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *CreateCommentOnMediaBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCommentOnMediaUnauthorized creates a CreateCommentOnMediaUnauthorized with default headers values
func NewCreateCommentOnMediaUnauthorized() *CreateCommentOnMediaUnauthorized {
	return &CreateCommentOnMediaUnauthorized{}
}

/*
CreateCommentOnMediaUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateCommentOnMediaUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this create comment on media unauthorized response has a 2xx status code
func (o *CreateCommentOnMediaUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create comment on media unauthorized response has a 3xx status code
func (o *CreateCommentOnMediaUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create comment on media unauthorized response has a 4xx status code
func (o *CreateCommentOnMediaUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create comment on media unauthorized response has a 5xx status code
func (o *CreateCommentOnMediaUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create comment on media unauthorized response a status code equal to that given
func (o *CreateCommentOnMediaUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateCommentOnMediaUnauthorized) Error() string {
	return fmt.Sprintf("[POST /{instagram_media_id}/comments][%d] createCommentOnMediaUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateCommentOnMediaUnauthorized) String() string {
	return fmt.Sprintf("[POST /{instagram_media_id}/comments][%d] createCommentOnMediaUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateCommentOnMediaUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *CreateCommentOnMediaUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCommentOnMediaForbidden creates a CreateCommentOnMediaForbidden with default headers values
func NewCreateCommentOnMediaForbidden() *CreateCommentOnMediaForbidden {
	return &CreateCommentOnMediaForbidden{}
}

/*
CreateCommentOnMediaForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateCommentOnMediaForbidden struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this create comment on media forbidden response has a 2xx status code
func (o *CreateCommentOnMediaForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create comment on media forbidden response has a 3xx status code
func (o *CreateCommentOnMediaForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create comment on media forbidden response has a 4xx status code
func (o *CreateCommentOnMediaForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create comment on media forbidden response has a 5xx status code
func (o *CreateCommentOnMediaForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create comment on media forbidden response a status code equal to that given
func (o *CreateCommentOnMediaForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateCommentOnMediaForbidden) Error() string {
	return fmt.Sprintf("[POST /{instagram_media_id}/comments][%d] createCommentOnMediaForbidden  %+v", 403, o.Payload)
}

func (o *CreateCommentOnMediaForbidden) String() string {
	return fmt.Sprintf("[POST /{instagram_media_id}/comments][%d] createCommentOnMediaForbidden  %+v", 403, o.Payload)
}

func (o *CreateCommentOnMediaForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *CreateCommentOnMediaForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCommentOnMediaNotFound creates a CreateCommentOnMediaNotFound with default headers values
func NewCreateCommentOnMediaNotFound() *CreateCommentOnMediaNotFound {
	return &CreateCommentOnMediaNotFound{}
}

/*
CreateCommentOnMediaNotFound describes a response with status code 404, with default header values.

Not found
*/
type CreateCommentOnMediaNotFound struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this create comment on media not found response has a 2xx status code
func (o *CreateCommentOnMediaNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create comment on media not found response has a 3xx status code
func (o *CreateCommentOnMediaNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create comment on media not found response has a 4xx status code
func (o *CreateCommentOnMediaNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create comment on media not found response has a 5xx status code
func (o *CreateCommentOnMediaNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create comment on media not found response a status code equal to that given
func (o *CreateCommentOnMediaNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *CreateCommentOnMediaNotFound) Error() string {
	return fmt.Sprintf("[POST /{instagram_media_id}/comments][%d] createCommentOnMediaNotFound  %+v", 404, o.Payload)
}

func (o *CreateCommentOnMediaNotFound) String() string {
	return fmt.Sprintf("[POST /{instagram_media_id}/comments][%d] createCommentOnMediaNotFound  %+v", 404, o.Payload)
}

func (o *CreateCommentOnMediaNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *CreateCommentOnMediaNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCommentOnMediaInternalServerError creates a CreateCommentOnMediaInternalServerError with default headers values
func NewCreateCommentOnMediaInternalServerError() *CreateCommentOnMediaInternalServerError {
	return &CreateCommentOnMediaInternalServerError{}
}

/*
CreateCommentOnMediaInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type CreateCommentOnMediaInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this create comment on media internal server error response has a 2xx status code
func (o *CreateCommentOnMediaInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create comment on media internal server error response has a 3xx status code
func (o *CreateCommentOnMediaInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create comment on media internal server error response has a 4xx status code
func (o *CreateCommentOnMediaInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create comment on media internal server error response has a 5xx status code
func (o *CreateCommentOnMediaInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create comment on media internal server error response a status code equal to that given
func (o *CreateCommentOnMediaInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *CreateCommentOnMediaInternalServerError) Error() string {
	return fmt.Sprintf("[POST /{instagram_media_id}/comments][%d] createCommentOnMediaInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateCommentOnMediaInternalServerError) String() string {
	return fmt.Sprintf("[POST /{instagram_media_id}/comments][%d] createCommentOnMediaInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateCommentOnMediaInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *CreateCommentOnMediaInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
