// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCommentsByMediaIDParams creates a new GetCommentsByMediaIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCommentsByMediaIDParams() *GetCommentsByMediaIDParams {
	return &GetCommentsByMediaIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCommentsByMediaIDParamsWithTimeout creates a new GetCommentsByMediaIDParams object
// with the ability to set a timeout on a request.
func NewGetCommentsByMediaIDParamsWithTimeout(timeout time.Duration) *GetCommentsByMediaIDParams {
	return &GetCommentsByMediaIDParams{
		timeout: timeout,
	}
}

// NewGetCommentsByMediaIDParamsWithContext creates a new GetCommentsByMediaIDParams object
// with the ability to set a context for a request.
func NewGetCommentsByMediaIDParamsWithContext(ctx context.Context) *GetCommentsByMediaIDParams {
	return &GetCommentsByMediaIDParams{
		Context: ctx,
	}
}

// NewGetCommentsByMediaIDParamsWithHTTPClient creates a new GetCommentsByMediaIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCommentsByMediaIDParamsWithHTTPClient(client *http.Client) *GetCommentsByMediaIDParams {
	return &GetCommentsByMediaIDParams{
		HTTPClient: client,
	}
}

/*
GetCommentsByMediaIDParams contains all the parameters to send to the API endpoint

	for the get comments by media ID operation.

	Typically these are written to a http.Request.
*/
type GetCommentsByMediaIDParams struct {

	/* XRequestID.

	   An unique ID for the request
	*/
	XRequestID *string

	/* InstagramMediaID.

	   Instagram Media ID
	*/
	InstagramMediaID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get comments by media ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCommentsByMediaIDParams) WithDefaults() *GetCommentsByMediaIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get comments by media ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCommentsByMediaIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get comments by media ID params
func (o *GetCommentsByMediaIDParams) WithTimeout(timeout time.Duration) *GetCommentsByMediaIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get comments by media ID params
func (o *GetCommentsByMediaIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get comments by media ID params
func (o *GetCommentsByMediaIDParams) WithContext(ctx context.Context) *GetCommentsByMediaIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get comments by media ID params
func (o *GetCommentsByMediaIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get comments by media ID params
func (o *GetCommentsByMediaIDParams) WithHTTPClient(client *http.Client) *GetCommentsByMediaIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get comments by media ID params
func (o *GetCommentsByMediaIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the get comments by media ID params
func (o *GetCommentsByMediaIDParams) WithXRequestID(xRequestID *string) *GetCommentsByMediaIDParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the get comments by media ID params
func (o *GetCommentsByMediaIDParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithInstagramMediaID adds the instagramMediaID to the get comments by media ID params
func (o *GetCommentsByMediaIDParams) WithInstagramMediaID(instagramMediaID string) *GetCommentsByMediaIDParams {
	o.SetInstagramMediaID(instagramMediaID)
	return o
}

// SetInstagramMediaID adds the instagramMediaId to the get comments by media ID params
func (o *GetCommentsByMediaIDParams) SetInstagramMediaID(instagramMediaID string) {
	o.InstagramMediaID = instagramMediaID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCommentsByMediaIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	// path param instagram_media_id
	if err := r.SetPathParam("instagram_media_id", o.InstagramMediaID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
