// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qcserestipy/instagram-api-go-client/pkg/sdk/v24.0/media/models"
)

// GetCommentsByMediaIDReader is a Reader for the GetCommentsByMediaID structure.
type GetCommentsByMediaIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCommentsByMediaIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCommentsByMediaIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCommentsByMediaIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetCommentsByMediaIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetCommentsByMediaIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCommentsByMediaIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCommentsByMediaIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCommentsByMediaIDOK creates a GetCommentsByMediaIDOK with default headers values
func NewGetCommentsByMediaIDOK() *GetCommentsByMediaIDOK {
	return &GetCommentsByMediaIDOK{}
}

/*
GetCommentsByMediaIDOK describes a response with status code 200, with default header values.

Return list of comments on the media object.
*/
type GetCommentsByMediaIDOK struct {
	Payload *models.InstagramComments
}

// IsSuccess returns true when this get comments by media Id o k response has a 2xx status code
func (o *GetCommentsByMediaIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get comments by media Id o k response has a 3xx status code
func (o *GetCommentsByMediaIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get comments by media Id o k response has a 4xx status code
func (o *GetCommentsByMediaIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get comments by media Id o k response has a 5xx status code
func (o *GetCommentsByMediaIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get comments by media Id o k response a status code equal to that given
func (o *GetCommentsByMediaIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetCommentsByMediaIDOK) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/comments][%d] getCommentsByMediaIdOK  %+v", 200, o.Payload)
}

func (o *GetCommentsByMediaIDOK) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/comments][%d] getCommentsByMediaIdOK  %+v", 200, o.Payload)
}

func (o *GetCommentsByMediaIDOK) GetPayload() *models.InstagramComments {
	return o.Payload
}

func (o *GetCommentsByMediaIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InstagramComments)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCommentsByMediaIDBadRequest creates a GetCommentsByMediaIDBadRequest with default headers values
func NewGetCommentsByMediaIDBadRequest() *GetCommentsByMediaIDBadRequest {
	return &GetCommentsByMediaIDBadRequest{}
}

/*
GetCommentsByMediaIDBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetCommentsByMediaIDBadRequest struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get comments by media Id bad request response has a 2xx status code
func (o *GetCommentsByMediaIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get comments by media Id bad request response has a 3xx status code
func (o *GetCommentsByMediaIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get comments by media Id bad request response has a 4xx status code
func (o *GetCommentsByMediaIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get comments by media Id bad request response has a 5xx status code
func (o *GetCommentsByMediaIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get comments by media Id bad request response a status code equal to that given
func (o *GetCommentsByMediaIDBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetCommentsByMediaIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/comments][%d] getCommentsByMediaIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetCommentsByMediaIDBadRequest) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/comments][%d] getCommentsByMediaIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetCommentsByMediaIDBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetCommentsByMediaIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCommentsByMediaIDUnauthorized creates a GetCommentsByMediaIDUnauthorized with default headers values
func NewGetCommentsByMediaIDUnauthorized() *GetCommentsByMediaIDUnauthorized {
	return &GetCommentsByMediaIDUnauthorized{}
}

/*
GetCommentsByMediaIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetCommentsByMediaIDUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get comments by media Id unauthorized response has a 2xx status code
func (o *GetCommentsByMediaIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get comments by media Id unauthorized response has a 3xx status code
func (o *GetCommentsByMediaIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get comments by media Id unauthorized response has a 4xx status code
func (o *GetCommentsByMediaIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get comments by media Id unauthorized response has a 5xx status code
func (o *GetCommentsByMediaIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get comments by media Id unauthorized response a status code equal to that given
func (o *GetCommentsByMediaIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetCommentsByMediaIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/comments][%d] getCommentsByMediaIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetCommentsByMediaIDUnauthorized) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/comments][%d] getCommentsByMediaIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetCommentsByMediaIDUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetCommentsByMediaIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCommentsByMediaIDForbidden creates a GetCommentsByMediaIDForbidden with default headers values
func NewGetCommentsByMediaIDForbidden() *GetCommentsByMediaIDForbidden {
	return &GetCommentsByMediaIDForbidden{}
}

/*
GetCommentsByMediaIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetCommentsByMediaIDForbidden struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get comments by media Id forbidden response has a 2xx status code
func (o *GetCommentsByMediaIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get comments by media Id forbidden response has a 3xx status code
func (o *GetCommentsByMediaIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get comments by media Id forbidden response has a 4xx status code
func (o *GetCommentsByMediaIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get comments by media Id forbidden response has a 5xx status code
func (o *GetCommentsByMediaIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get comments by media Id forbidden response a status code equal to that given
func (o *GetCommentsByMediaIDForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetCommentsByMediaIDForbidden) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/comments][%d] getCommentsByMediaIdForbidden  %+v", 403, o.Payload)
}

func (o *GetCommentsByMediaIDForbidden) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/comments][%d] getCommentsByMediaIdForbidden  %+v", 403, o.Payload)
}

func (o *GetCommentsByMediaIDForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetCommentsByMediaIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCommentsByMediaIDNotFound creates a GetCommentsByMediaIDNotFound with default headers values
func NewGetCommentsByMediaIDNotFound() *GetCommentsByMediaIDNotFound {
	return &GetCommentsByMediaIDNotFound{}
}

/*
GetCommentsByMediaIDNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetCommentsByMediaIDNotFound struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get comments by media Id not found response has a 2xx status code
func (o *GetCommentsByMediaIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get comments by media Id not found response has a 3xx status code
func (o *GetCommentsByMediaIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get comments by media Id not found response has a 4xx status code
func (o *GetCommentsByMediaIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get comments by media Id not found response has a 5xx status code
func (o *GetCommentsByMediaIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get comments by media Id not found response a status code equal to that given
func (o *GetCommentsByMediaIDNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetCommentsByMediaIDNotFound) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/comments][%d] getCommentsByMediaIdNotFound  %+v", 404, o.Payload)
}

func (o *GetCommentsByMediaIDNotFound) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/comments][%d] getCommentsByMediaIdNotFound  %+v", 404, o.Payload)
}

func (o *GetCommentsByMediaIDNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetCommentsByMediaIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCommentsByMediaIDInternalServerError creates a GetCommentsByMediaIDInternalServerError with default headers values
func NewGetCommentsByMediaIDInternalServerError() *GetCommentsByMediaIDInternalServerError {
	return &GetCommentsByMediaIDInternalServerError{}
}

/*
GetCommentsByMediaIDInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetCommentsByMediaIDInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get comments by media Id internal server error response has a 2xx status code
func (o *GetCommentsByMediaIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get comments by media Id internal server error response has a 3xx status code
func (o *GetCommentsByMediaIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get comments by media Id internal server error response has a 4xx status code
func (o *GetCommentsByMediaIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get comments by media Id internal server error response has a 5xx status code
func (o *GetCommentsByMediaIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get comments by media Id internal server error response a status code equal to that given
func (o *GetCommentsByMediaIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetCommentsByMediaIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/comments][%d] getCommentsByMediaIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCommentsByMediaIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/comments][%d] getCommentsByMediaIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCommentsByMediaIDInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetCommentsByMediaIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
