// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qcserestipy/instagram-api-go-client/pkg/sdk/v24.0/account/models"
)

// GetInstagramUserByIDReader is a Reader for the GetInstagramUserByID structure.
type GetInstagramUserByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInstagramUserByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInstagramUserByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetInstagramUserByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetInstagramUserByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetInstagramUserByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetInstagramUserByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetInstagramUserByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /{instagram_account_id}] GetInstagramUserByID", response, response.Code())
	}
}

// NewGetInstagramUserByIDOK creates a GetInstagramUserByIDOK with default headers values
func NewGetInstagramUserByIDOK() *GetInstagramUserByIDOK {
	return &GetInstagramUserByIDOK{}
}

/*
GetInstagramUserByIDOK describes a response with status code 200, with default header values.

Return Instagram User object with requested fields.
*/
type GetInstagramUserByIDOK struct {
	Payload *models.InstagramUser
}

// IsSuccess returns true when this get instagram user by Id o k response has a 2xx status code
func (o *GetInstagramUserByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get instagram user by Id o k response has a 3xx status code
func (o *GetInstagramUserByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get instagram user by Id o k response has a 4xx status code
func (o *GetInstagramUserByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get instagram user by Id o k response has a 5xx status code
func (o *GetInstagramUserByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get instagram user by Id o k response a status code equal to that given
func (o *GetInstagramUserByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get instagram user by Id o k response
func (o *GetInstagramUserByIDOK) Code() int {
	return 200
}

func (o *GetInstagramUserByIDOK) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}][%d] getInstagramUserByIdOK  %+v", 200, o.Payload)
}

func (o *GetInstagramUserByIDOK) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}][%d] getInstagramUserByIdOK  %+v", 200, o.Payload)
}

func (o *GetInstagramUserByIDOK) GetPayload() *models.InstagramUser {
	return o.Payload
}

func (o *GetInstagramUserByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InstagramUser)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInstagramUserByIDBadRequest creates a GetInstagramUserByIDBadRequest with default headers values
func NewGetInstagramUserByIDBadRequest() *GetInstagramUserByIDBadRequest {
	return &GetInstagramUserByIDBadRequest{}
}

/*
GetInstagramUserByIDBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetInstagramUserByIDBadRequest struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get instagram user by Id bad request response has a 2xx status code
func (o *GetInstagramUserByIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get instagram user by Id bad request response has a 3xx status code
func (o *GetInstagramUserByIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get instagram user by Id bad request response has a 4xx status code
func (o *GetInstagramUserByIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get instagram user by Id bad request response has a 5xx status code
func (o *GetInstagramUserByIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get instagram user by Id bad request response a status code equal to that given
func (o *GetInstagramUserByIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get instagram user by Id bad request response
func (o *GetInstagramUserByIDBadRequest) Code() int {
	return 400
}

func (o *GetInstagramUserByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}][%d] getInstagramUserByIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetInstagramUserByIDBadRequest) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}][%d] getInstagramUserByIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetInstagramUserByIDBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetInstagramUserByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInstagramUserByIDUnauthorized creates a GetInstagramUserByIDUnauthorized with default headers values
func NewGetInstagramUserByIDUnauthorized() *GetInstagramUserByIDUnauthorized {
	return &GetInstagramUserByIDUnauthorized{}
}

/*
GetInstagramUserByIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetInstagramUserByIDUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get instagram user by Id unauthorized response has a 2xx status code
func (o *GetInstagramUserByIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get instagram user by Id unauthorized response has a 3xx status code
func (o *GetInstagramUserByIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get instagram user by Id unauthorized response has a 4xx status code
func (o *GetInstagramUserByIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get instagram user by Id unauthorized response has a 5xx status code
func (o *GetInstagramUserByIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get instagram user by Id unauthorized response a status code equal to that given
func (o *GetInstagramUserByIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get instagram user by Id unauthorized response
func (o *GetInstagramUserByIDUnauthorized) Code() int {
	return 401
}

func (o *GetInstagramUserByIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}][%d] getInstagramUserByIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetInstagramUserByIDUnauthorized) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}][%d] getInstagramUserByIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetInstagramUserByIDUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetInstagramUserByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInstagramUserByIDForbidden creates a GetInstagramUserByIDForbidden with default headers values
func NewGetInstagramUserByIDForbidden() *GetInstagramUserByIDForbidden {
	return &GetInstagramUserByIDForbidden{}
}

/*
GetInstagramUserByIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetInstagramUserByIDForbidden struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get instagram user by Id forbidden response has a 2xx status code
func (o *GetInstagramUserByIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get instagram user by Id forbidden response has a 3xx status code
func (o *GetInstagramUserByIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get instagram user by Id forbidden response has a 4xx status code
func (o *GetInstagramUserByIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get instagram user by Id forbidden response has a 5xx status code
func (o *GetInstagramUserByIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get instagram user by Id forbidden response a status code equal to that given
func (o *GetInstagramUserByIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get instagram user by Id forbidden response
func (o *GetInstagramUserByIDForbidden) Code() int {
	return 403
}

func (o *GetInstagramUserByIDForbidden) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}][%d] getInstagramUserByIdForbidden  %+v", 403, o.Payload)
}

func (o *GetInstagramUserByIDForbidden) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}][%d] getInstagramUserByIdForbidden  %+v", 403, o.Payload)
}

func (o *GetInstagramUserByIDForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetInstagramUserByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInstagramUserByIDNotFound creates a GetInstagramUserByIDNotFound with default headers values
func NewGetInstagramUserByIDNotFound() *GetInstagramUserByIDNotFound {
	return &GetInstagramUserByIDNotFound{}
}

/*
GetInstagramUserByIDNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetInstagramUserByIDNotFound struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get instagram user by Id not found response has a 2xx status code
func (o *GetInstagramUserByIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get instagram user by Id not found response has a 3xx status code
func (o *GetInstagramUserByIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get instagram user by Id not found response has a 4xx status code
func (o *GetInstagramUserByIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get instagram user by Id not found response has a 5xx status code
func (o *GetInstagramUserByIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get instagram user by Id not found response a status code equal to that given
func (o *GetInstagramUserByIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get instagram user by Id not found response
func (o *GetInstagramUserByIDNotFound) Code() int {
	return 404
}

func (o *GetInstagramUserByIDNotFound) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}][%d] getInstagramUserByIdNotFound  %+v", 404, o.Payload)
}

func (o *GetInstagramUserByIDNotFound) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}][%d] getInstagramUserByIdNotFound  %+v", 404, o.Payload)
}

func (o *GetInstagramUserByIDNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetInstagramUserByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInstagramUserByIDInternalServerError creates a GetInstagramUserByIDInternalServerError with default headers values
func NewGetInstagramUserByIDInternalServerError() *GetInstagramUserByIDInternalServerError {
	return &GetInstagramUserByIDInternalServerError{}
}

/*
GetInstagramUserByIDInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetInstagramUserByIDInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get instagram user by Id internal server error response has a 2xx status code
func (o *GetInstagramUserByIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get instagram user by Id internal server error response has a 3xx status code
func (o *GetInstagramUserByIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get instagram user by Id internal server error response has a 4xx status code
func (o *GetInstagramUserByIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get instagram user by Id internal server error response has a 5xx status code
func (o *GetInstagramUserByIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get instagram user by Id internal server error response a status code equal to that given
func (o *GetInstagramUserByIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get instagram user by Id internal server error response
func (o *GetInstagramUserByIDInternalServerError) Code() int {
	return 500
}

func (o *GetInstagramUserByIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /{instagram_account_id}][%d] getInstagramUserByIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetInstagramUserByIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /{instagram_account_id}][%d] getInstagramUserByIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetInstagramUserByIDInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetInstagramUserByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
