// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInstagramUserByIDParams creates a new GetInstagramUserByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInstagramUserByIDParams() *GetInstagramUserByIDParams {
	return &GetInstagramUserByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstagramUserByIDParamsWithTimeout creates a new GetInstagramUserByIDParams object
// with the ability to set a timeout on a request.
func NewGetInstagramUserByIDParamsWithTimeout(timeout time.Duration) *GetInstagramUserByIDParams {
	return &GetInstagramUserByIDParams{
		timeout: timeout,
	}
}

// NewGetInstagramUserByIDParamsWithContext creates a new GetInstagramUserByIDParams object
// with the ability to set a context for a request.
func NewGetInstagramUserByIDParamsWithContext(ctx context.Context) *GetInstagramUserByIDParams {
	return &GetInstagramUserByIDParams{
		Context: ctx,
	}
}

// NewGetInstagramUserByIDParamsWithHTTPClient creates a new GetInstagramUserByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInstagramUserByIDParamsWithHTTPClient(client *http.Client) *GetInstagramUserByIDParams {
	return &GetInstagramUserByIDParams{
		HTTPClient: client,
	}
}

/*
GetInstagramUserByIDParams contains all the parameters to send to the API endpoint

	for the get instagram user by ID operation.

	Typically these are written to a http.Request.
*/
type GetInstagramUserByIDParams struct {

	/* XRequestID.

	   An unique ID for the request
	*/
	XRequestID *string

	/* Fields.

	   Comma-separated list of fields to return for the IG User (e.g. id,username,biography,followers_count,media_count,profile_picture_url,website). Only requested fields will be returned.
	*/
	Fields *string

	/* InstagramAccountID.

	   Instagram Account ID (your app user's Instagram professional account ID)
	*/
	InstagramAccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get instagram user by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstagramUserByIDParams) WithDefaults() *GetInstagramUserByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get instagram user by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstagramUserByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get instagram user by ID params
func (o *GetInstagramUserByIDParams) WithTimeout(timeout time.Duration) *GetInstagramUserByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get instagram user by ID params
func (o *GetInstagramUserByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get instagram user by ID params
func (o *GetInstagramUserByIDParams) WithContext(ctx context.Context) *GetInstagramUserByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get instagram user by ID params
func (o *GetInstagramUserByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get instagram user by ID params
func (o *GetInstagramUserByIDParams) WithHTTPClient(client *http.Client) *GetInstagramUserByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get instagram user by ID params
func (o *GetInstagramUserByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the get instagram user by ID params
func (o *GetInstagramUserByIDParams) WithXRequestID(xRequestID *string) *GetInstagramUserByIDParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the get instagram user by ID params
func (o *GetInstagramUserByIDParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithFields adds the fields to the get instagram user by ID params
func (o *GetInstagramUserByIDParams) WithFields(fields *string) *GetInstagramUserByIDParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get instagram user by ID params
func (o *GetInstagramUserByIDParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithInstagramAccountID adds the instagramAccountID to the get instagram user by ID params
func (o *GetInstagramUserByIDParams) WithInstagramAccountID(instagramAccountID string) *GetInstagramUserByIDParams {
	o.SetInstagramAccountID(instagramAccountID)
	return o
}

// SetInstagramAccountID adds the instagramAccountId to the get instagram user by ID params
func (o *GetInstagramUserByIDParams) SetInstagramAccountID(instagramAccountID string) {
	o.InstagramAccountID = instagramAccountID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstagramUserByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	// path param instagram_account_id
	if err := r.SetPathParam("instagram_account_id", o.InstagramAccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
