// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery --name API --keeptree --with-expecter --case underscore

// API is the interface of the user client
type API interface {
	/*
	   GetInstagramUserByID gets fields and edges on an instagram user

	   Get fields and edges on an Instagram Business or Creator Account.
	   This endpoint returns the requested public fields and available edges for the targeted Instagram professional account.

	   Edges available on an Instagram User include: media, stories, insights, mentions, tags, mentioned_media, mentioned_comment, business_discovery, and others depending on permissions.
	*/
	GetInstagramUserByID(ctx context.Context, params *GetInstagramUserByIDParams) (*GetInstagramUserByIDOK, error)
}

// New creates a new user API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for user API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
GetInstagramUserByID gets fields and edges on an instagram user

Get fields and edges on an Instagram Business or Creator Account.
This endpoint returns the requested public fields and available edges for the targeted Instagram professional account.

Edges available on an Instagram User include: media, stories, insights, mentions, tags, mentioned_media, mentioned_comment, business_discovery, and others depending on permissions.
*/
func (a *Client) GetInstagramUserByID(ctx context.Context, params *GetInstagramUserByIDParams) (*GetInstagramUserByIDOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetInstagramUserByID",
		Method:             "GET",
		PathPattern:        "/{instagram_account_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetInstagramUserByIDReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	switch value := result.(type) {
	case *GetInstagramUserByIDOK:
		return value, nil
	case *GetInstagramUserByIDBadRequest:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetInstagramUserByIDUnauthorized:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetInstagramUserByIDForbidden:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetInstagramUserByIDNotFound:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetInstagramUserByIDInternalServerError:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetInstagramUserByID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}
