// Code generated by go-swagger; DO NOT EDIT.

package insights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInsightsByMediaIDParams creates a new GetInsightsByMediaIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInsightsByMediaIDParams() *GetInsightsByMediaIDParams {
	return &GetInsightsByMediaIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInsightsByMediaIDParamsWithTimeout creates a new GetInsightsByMediaIDParams object
// with the ability to set a timeout on a request.
func NewGetInsightsByMediaIDParamsWithTimeout(timeout time.Duration) *GetInsightsByMediaIDParams {
	return &GetInsightsByMediaIDParams{
		timeout: timeout,
	}
}

// NewGetInsightsByMediaIDParamsWithContext creates a new GetInsightsByMediaIDParams object
// with the ability to set a context for a request.
func NewGetInsightsByMediaIDParamsWithContext(ctx context.Context) *GetInsightsByMediaIDParams {
	return &GetInsightsByMediaIDParams{
		Context: ctx,
	}
}

// NewGetInsightsByMediaIDParamsWithHTTPClient creates a new GetInsightsByMediaIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInsightsByMediaIDParamsWithHTTPClient(client *http.Client) *GetInsightsByMediaIDParams {
	return &GetInsightsByMediaIDParams{
		HTTPClient: client,
	}
}

/*
GetInsightsByMediaIDParams contains all the parameters to send to the API endpoint

	for the get insights by media ID operation.

	Typically these are written to a http.Request.
*/
type GetInsightsByMediaIDParams struct {

	/* XRequestID.

	   An unique ID for the request
	*/
	XRequestID *string

	/* Breakdown.

	     Designates how to break down results into subsets. Values can be:
	- action_type (only compatible with profile_activity metric)
	- story_navigation_action_type (only compatible with navigation metric)

	*/
	Breakdown *string

	/* InstagramMediaID.

	   Instagram Media ID
	*/
	InstagramMediaID string

	/* Metric.

	     Required. Comma-separated list of metrics you want returned. Available metrics include:
	- clips_replays_count (REELS - deprecated)
	- comments (FEED, REELS)
	- follows (FEED, STORY)
	- ig_reels_aggregated_all_plays_count (REELS - deprecated)
	- ig_reels_avg_watch_time (REELS)
	- ig_reels_video_view_total_time (REELS)
	- impressions (FEED, STORY - deprecated for new media)
	- likes (FEED, REELS)
	- navigation (STORY)
	- plays (REELS - deprecated)
	- profile_activity (FEED, STORY)
	- profile_visits (FEED, STORY)
	- reach (FEED, REELS, STORY)
	- replies (STORY)
	- saved (FEED, REELS)
	- shares (FEED, REELS, STORY)
	- total_interactions (FEED, REELS, STORY)
	- views (FEED, REELS, STORY)

	*/
	Metric string

	/* MetricType.

	     The type of metric. Values can be:
	- total_value (for certain metrics like likes, comments, shares)
	- time_series

	*/
	MetricType *string

	/* Period.

	     Required. Comma-separated list of time periods you want returned. Values can be:
	- day
	- week
	- days_28
	- month
	- lifetime
	- total_over_range

	*/
	Period string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get insights by media ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInsightsByMediaIDParams) WithDefaults() *GetInsightsByMediaIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get insights by media ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInsightsByMediaIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) WithTimeout(timeout time.Duration) *GetInsightsByMediaIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) WithContext(ctx context.Context) *GetInsightsByMediaIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) WithHTTPClient(client *http.Client) *GetInsightsByMediaIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) WithXRequestID(xRequestID *string) *GetInsightsByMediaIDParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithBreakdown adds the breakdown to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) WithBreakdown(breakdown *string) *GetInsightsByMediaIDParams {
	o.SetBreakdown(breakdown)
	return o
}

// SetBreakdown adds the breakdown to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) SetBreakdown(breakdown *string) {
	o.Breakdown = breakdown
}

// WithInstagramMediaID adds the instagramMediaID to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) WithInstagramMediaID(instagramMediaID string) *GetInsightsByMediaIDParams {
	o.SetInstagramMediaID(instagramMediaID)
	return o
}

// SetInstagramMediaID adds the instagramMediaId to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) SetInstagramMediaID(instagramMediaID string) {
	o.InstagramMediaID = instagramMediaID
}

// WithMetric adds the metric to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) WithMetric(metric string) *GetInsightsByMediaIDParams {
	o.SetMetric(metric)
	return o
}

// SetMetric adds the metric to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) SetMetric(metric string) {
	o.Metric = metric
}

// WithMetricType adds the metricType to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) WithMetricType(metricType *string) *GetInsightsByMediaIDParams {
	o.SetMetricType(metricType)
	return o
}

// SetMetricType adds the metricType to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) SetMetricType(metricType *string) {
	o.MetricType = metricType
}

// WithPeriod adds the period to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) WithPeriod(period string) *GetInsightsByMediaIDParams {
	o.SetPeriod(period)
	return o
}

// SetPeriod adds the period to the get insights by media ID params
func (o *GetInsightsByMediaIDParams) SetPeriod(period string) {
	o.Period = period
}

// WriteToRequest writes these params to a swagger request
func (o *GetInsightsByMediaIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	if o.Breakdown != nil {

		// query param breakdown
		var qrBreakdown string

		if o.Breakdown != nil {
			qrBreakdown = *o.Breakdown
		}
		qBreakdown := qrBreakdown
		if qBreakdown != "" {

			if err := r.SetQueryParam("breakdown", qBreakdown); err != nil {
				return err
			}
		}
	}

	// path param instagram_media_id
	if err := r.SetPathParam("instagram_media_id", o.InstagramMediaID); err != nil {
		return err
	}

	// query param metric
	qrMetric := o.Metric
	qMetric := qrMetric
	if qMetric != "" {

		if err := r.SetQueryParam("metric", qMetric); err != nil {
			return err
		}
	}

	if o.MetricType != nil {

		// query param metric_type
		var qrMetricType string

		if o.MetricType != nil {
			qrMetricType = *o.MetricType
		}
		qMetricType := qrMetricType
		if qMetricType != "" {

			if err := r.SetQueryParam("metric_type", qMetricType); err != nil {
				return err
			}
		}
	}

	// query param period
	qrPeriod := o.Period
	qPeriod := qrPeriod
	if qPeriod != "" {

		if err := r.SetQueryParam("period", qPeriod); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
