// Code generated by go-swagger; DO NOT EDIT.

package insights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qcserestipy/insta-swagger/pkg/sdk/v24.0/models"
)

// GetInsightsByMediaIDReader is a Reader for the GetInsightsByMediaID structure.
type GetInsightsByMediaIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInsightsByMediaIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInsightsByMediaIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetInsightsByMediaIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetInsightsByMediaIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetInsightsByMediaIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetInsightsByMediaIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetInsightsByMediaIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetInsightsByMediaIDOK creates a GetInsightsByMediaIDOK with default headers values
func NewGetInsightsByMediaIDOK() *GetInsightsByMediaIDOK {
	return &GetInsightsByMediaIDOK{}
}

/*
GetInsightsByMediaIDOK describes a response with status code 200, with default header values.

Return matched Instagram Media insights.
*/
type GetInsightsByMediaIDOK struct {
	Payload *models.InstagramMediaInsights
}

// IsSuccess returns true when this get insights by media Id o k response has a 2xx status code
func (o *GetInsightsByMediaIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get insights by media Id o k response has a 3xx status code
func (o *GetInsightsByMediaIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get insights by media Id o k response has a 4xx status code
func (o *GetInsightsByMediaIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get insights by media Id o k response has a 5xx status code
func (o *GetInsightsByMediaIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get insights by media Id o k response a status code equal to that given
func (o *GetInsightsByMediaIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetInsightsByMediaIDOK) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/insights][%d] getInsightsByMediaIdOK  %+v", 200, o.Payload)
}

func (o *GetInsightsByMediaIDOK) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/insights][%d] getInsightsByMediaIdOK  %+v", 200, o.Payload)
}

func (o *GetInsightsByMediaIDOK) GetPayload() *models.InstagramMediaInsights {
	return o.Payload
}

func (o *GetInsightsByMediaIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InstagramMediaInsights)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInsightsByMediaIDBadRequest creates a GetInsightsByMediaIDBadRequest with default headers values
func NewGetInsightsByMediaIDBadRequest() *GetInsightsByMediaIDBadRequest {
	return &GetInsightsByMediaIDBadRequest{}
}

/*
GetInsightsByMediaIDBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetInsightsByMediaIDBadRequest struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get insights by media Id bad request response has a 2xx status code
func (o *GetInsightsByMediaIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get insights by media Id bad request response has a 3xx status code
func (o *GetInsightsByMediaIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get insights by media Id bad request response has a 4xx status code
func (o *GetInsightsByMediaIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get insights by media Id bad request response has a 5xx status code
func (o *GetInsightsByMediaIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get insights by media Id bad request response a status code equal to that given
func (o *GetInsightsByMediaIDBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetInsightsByMediaIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/insights][%d] getInsightsByMediaIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetInsightsByMediaIDBadRequest) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/insights][%d] getInsightsByMediaIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetInsightsByMediaIDBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetInsightsByMediaIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInsightsByMediaIDUnauthorized creates a GetInsightsByMediaIDUnauthorized with default headers values
func NewGetInsightsByMediaIDUnauthorized() *GetInsightsByMediaIDUnauthorized {
	return &GetInsightsByMediaIDUnauthorized{}
}

/*
GetInsightsByMediaIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetInsightsByMediaIDUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get insights by media Id unauthorized response has a 2xx status code
func (o *GetInsightsByMediaIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get insights by media Id unauthorized response has a 3xx status code
func (o *GetInsightsByMediaIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get insights by media Id unauthorized response has a 4xx status code
func (o *GetInsightsByMediaIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get insights by media Id unauthorized response has a 5xx status code
func (o *GetInsightsByMediaIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get insights by media Id unauthorized response a status code equal to that given
func (o *GetInsightsByMediaIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetInsightsByMediaIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/insights][%d] getInsightsByMediaIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetInsightsByMediaIDUnauthorized) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/insights][%d] getInsightsByMediaIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetInsightsByMediaIDUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetInsightsByMediaIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInsightsByMediaIDForbidden creates a GetInsightsByMediaIDForbidden with default headers values
func NewGetInsightsByMediaIDForbidden() *GetInsightsByMediaIDForbidden {
	return &GetInsightsByMediaIDForbidden{}
}

/*
GetInsightsByMediaIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetInsightsByMediaIDForbidden struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get insights by media Id forbidden response has a 2xx status code
func (o *GetInsightsByMediaIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get insights by media Id forbidden response has a 3xx status code
func (o *GetInsightsByMediaIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get insights by media Id forbidden response has a 4xx status code
func (o *GetInsightsByMediaIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get insights by media Id forbidden response has a 5xx status code
func (o *GetInsightsByMediaIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get insights by media Id forbidden response a status code equal to that given
func (o *GetInsightsByMediaIDForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetInsightsByMediaIDForbidden) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/insights][%d] getInsightsByMediaIdForbidden  %+v", 403, o.Payload)
}

func (o *GetInsightsByMediaIDForbidden) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/insights][%d] getInsightsByMediaIdForbidden  %+v", 403, o.Payload)
}

func (o *GetInsightsByMediaIDForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetInsightsByMediaIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInsightsByMediaIDNotFound creates a GetInsightsByMediaIDNotFound with default headers values
func NewGetInsightsByMediaIDNotFound() *GetInsightsByMediaIDNotFound {
	return &GetInsightsByMediaIDNotFound{}
}

/*
GetInsightsByMediaIDNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetInsightsByMediaIDNotFound struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get insights by media Id not found response has a 2xx status code
func (o *GetInsightsByMediaIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get insights by media Id not found response has a 3xx status code
func (o *GetInsightsByMediaIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get insights by media Id not found response has a 4xx status code
func (o *GetInsightsByMediaIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get insights by media Id not found response has a 5xx status code
func (o *GetInsightsByMediaIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get insights by media Id not found response a status code equal to that given
func (o *GetInsightsByMediaIDNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetInsightsByMediaIDNotFound) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/insights][%d] getInsightsByMediaIdNotFound  %+v", 404, o.Payload)
}

func (o *GetInsightsByMediaIDNotFound) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/insights][%d] getInsightsByMediaIdNotFound  %+v", 404, o.Payload)
}

func (o *GetInsightsByMediaIDNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetInsightsByMediaIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInsightsByMediaIDInternalServerError creates a GetInsightsByMediaIDInternalServerError with default headers values
func NewGetInsightsByMediaIDInternalServerError() *GetInsightsByMediaIDInternalServerError {
	return &GetInsightsByMediaIDInternalServerError{}
}

/*
GetInsightsByMediaIDInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetInsightsByMediaIDInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get insights by media Id internal server error response has a 2xx status code
func (o *GetInsightsByMediaIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get insights by media Id internal server error response has a 3xx status code
func (o *GetInsightsByMediaIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get insights by media Id internal server error response has a 4xx status code
func (o *GetInsightsByMediaIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get insights by media Id internal server error response has a 5xx status code
func (o *GetInsightsByMediaIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get insights by media Id internal server error response a status code equal to that given
func (o *GetInsightsByMediaIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetInsightsByMediaIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/insights][%d] getInsightsByMediaIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetInsightsByMediaIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /{instagram_media_id}/insights][%d] getInsightsByMediaIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetInsightsByMediaIDInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetInsightsByMediaIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
