// Code generated by go-swagger; DO NOT EDIT.

package insights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery -name API -inpkg

// API is the interface of the insights client
type API interface {
	/*
	   GetInsightsByMediaID gets insights data on an instagram media object

	   Get insights data on an Instagram Media object.

	   Limitations:
	   - If insights data you are requesting does not exist or is currently unavailable, the API returns an empty data set instead of 0 for individual metrics.
	   - Data used to calculate metrics can be delayed up to 48 hours.
	   - Metrics data is stored for up to 2 years.
	   - The API only reports organic interaction metrics; interactions on ads containing a media object are not counted.
	   - Story media metrics are only available for 24 hours.
	   - Story media metrics with values less than 5 return an error code 10.
	*/
	GetInsightsByMediaID(ctx context.Context, params *GetInsightsByMediaIDParams) (*GetInsightsByMediaIDOK, error)
}

// New creates a new insights API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for insights API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
GetInsightsByMediaID gets insights data on an instagram media object

Get insights data on an Instagram Media object.

Limitations:
- If insights data you are requesting does not exist or is currently unavailable, the API returns an empty data set instead of 0 for individual metrics.
- Data used to calculate metrics can be delayed up to 48 hours.
- Metrics data is stored for up to 2 years.
- The API only reports organic interaction metrics; interactions on ads containing a media object are not counted.
- Story media metrics are only available for 24 hours.
- Story media metrics with values less than 5 return an error code 10.
*/
func (a *Client) GetInsightsByMediaID(ctx context.Context, params *GetInsightsByMediaIDParams) (*GetInsightsByMediaIDOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetInsightsByMediaID",
		Method:             "GET",
		PathPattern:        "/{instagram_media_id}/insights",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetInsightsByMediaIDReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetInsightsByMediaIDOK), nil

}
